/**
 * L12 BULLET 4, first half — THE FINAL VISUAL ATLAS.
 *
 * This assembles an atlas from an `l12-visual-matrix/v1` manifest: a coverage-accounted
 * index of every captured cell, a human-viewable contact sheet, and a verdict on whether
 * the run may be called certification evidence at all.
 *
 * WHY IT IS A SEPARATE MODULE FROM THE HARNESS THAT PRODUCES THE MANIFEST, decided here
 * and recorded so it is not "tidied" back:
 *
 *   1. `l12-visual-matrix.cjs` REFUSES without `debug/bridge.json` — it is a live
 *      instrument. An atlas welded into it could only ever be regenerated by re-running
 *      the whole matrix against a running app. The release handoff's atlas has to be
 *      rebuildable from BANKED evidence, years after the app that produced it stopped
 *      running, so the assembler takes a file and touches no bridge.
 *   2. Bullet 1 (the matrix) and bullet 4 (the atlas) have different owners working
 *      concurrently in different trees. Two workers editing one 750-line file is how work
 *      is lost here.
 *
 * The harness's reserved `--atlas` flag stays meaningful: it shells out to this file after
 * a run, so the flag is a pass-through rather than a second implementation.
 *
 * ---------------------------------------------------------------------------------
 * WHAT AN ATLAS CAN LIE ABOUT, AND THE FOUR CHECKS THAT STOP IT.
 *
 * A wall of 182 screenshots is the single most convincing artifact this plan can produce
 * and it proves nothing by itself. Every failure below is one this repo has already
 * committed at least once in some other instrument.
 *
 * (A) COVERAGE THAT IS ASSERTED RATHER THAN COUNTED. The atlas recomputes the full
 *     cartesian product |apps| x |themes| x |presentations| x |states| from the
 *     manifest's OWN declared dimensions and subtracts what is actually present. A cell
 *     that was never attempted and a cell that failed are different numbers and are
 *     reported as different numbers. `sampledOut` sections are listed BY NAME (RULE C
 *     forbids silent truncation) and the atlas states its coverage of the canonical
 *     section universe, not just of what was requested.
 *
 * (B) A DECORATIVE AXIS. This is the C4 defect one level up. The matrix's first draft
 *     captured the whole renderer, so the "app" axis moved no pixels and the run still
 *     looked complete; a `rect` crop fixed it and control C4 keeps it honest. The atlas
 *     applies the same question to EVERY axis mechanically: hold three axes fixed, vary
 *     the fourth, and count how many DISTINCT sha256s come back. An axis whose every
 *     comparable group returns exactly one distinct image moved nothing, and an atlas
 *     built on it is claiming a dimension of coverage it does not have. That axis is
 *     reported `decorative` and the atlas is NOT certifiable.
 *
 *     Live finding this check was written against, and it fired on its first run: the
 *     matrix accepts `--states normal,maximized` in its own usage line but the state
 *     loop drives nothing -- no code reaches a maximize control -- so two passes would
 *     bank identical images under two labels. Reported, not silently repaired: that file
 *     belongs to bullet 1 and to another worker.
 *
 * (C) BYTES THAT ARE NOT THERE. `debug/` is gitignored, so the PNGs an atlas indexes are
 *     deleted the moment anyone cleans the tree, while the JSON keeps asserting they
 *     exist at a given size and hash. Every cell is therefore re-hashed FROM DISK at
 *     assembly time and lands in one of three honest states -- `verified` (present and
 *     the hash matches), `missing` (indexed but not on disk), `mismatch` (present and the
 *     hash does NOT match, which means something rewrote it). An atlas whose images are
 *     all `missing` is still a legitimate artifact -- the sha256s remain checkable
 *     against any future re-run -- but it says so in its own verdict instead of implying
 *     a picture wall that no longer exists.
 *
 * (D) DUPLICATES PASSED OFF AS COVERAGE. Cells sharing one sha256 are grouped and counted.
 *     Some duplication is legitimate (an app with no Liquid toggle photographs identically
 *     in both presentations, and the manifest says why); duplication ACROSS a must-differ
 *     axis is check (B). The raw number is published either way.
 *
 * ---------------------------------------------------------------------------------
 * THE MUTATION CONTROL, `--control`. Four checks that all pass on good input tell you
 * nothing about whether they can fail. Each control below damages an in-memory COPY of
 * the manifest in one specific way and asserts the corresponding check reports it:
 *
 *   M1  drop one cell            -> coverage must report exactly one more missing cell
 *   M2  flatten one axis's shas  -> that axis must be reported decorative
 *   M3  corrupt one sha256       -> integrity must report a mismatch (needs the PNG on
 *                                   disk; with the images cleaned it reports `n/a`
 *                                   rather than a pass it did not earn)
 *   M4  drop a whole app's cells -> app coverage must fall by exactly that app
 *
 * A control that cannot run says `n/a` with its reason. It never scores a pass.
 *
 * ---------------------------------------------------------------------------------
 * Run:
 *   node src/.coordination/liquid-workplace/probes/l12-atlas.cjs \
 *     [--manifest a.json[,b.json,...]] [--out <atlas.json>] \
 *     [--sheet debug/shots/l12-atlas.html] [--control]
 *
 * `--manifest` takes a comma-separated LIST and order is precedence — a later manifest
 * supersedes an earlier one on the same cell coordinate. See `mergeManifests` for why
 * bullet 1's evidence is three runs and what the merge is allowed to combine.
 *
 * WHAT IS COMMITTED: the atlas JSON only. The contact sheet is HTML that references
 * gitignored PNGs by relative path, so it lands in `debug/shots/` beside them.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const REPO = path.join(__dirname, '..', '..', '..', '..');
const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : dflt;
};
const has = (name) => process.argv.indexOf(`--${name}`) >= 0;

const AXES = ['app', 'theme', 'presentation', 'state'];

/** The key of a cell with one axis removed — the group inside which that axis varies. */
function groupKey(cell, without) {
  return AXES.filter((a) => a !== without).map((a) => `${a}=${cell[a]}`).join('|');
}

/**
 * Check (B). For one axis: partition the captured cells by everything EXCEPT that axis,
 * and inside each partition count distinct images. A partition with a single member
 * cannot falsify anything and is excluded from the verdict rather than counted as a pass.
 */
function axisEffect(cells, axis) {
  const groups = new Map();
  for (const c of cells) {
    if (!c.ok || !c.sha256) continue;
    const k = groupKey(c, axis);
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(c);
  }
  let comparable = 0;
  let moved = 0;
  let geometryMoved = 0;
  const flat = [];
  for (const [k, list] of groups) {
    if (list.length < 2) continue;
    comparable += 1;
    const distinct = new Set(list.map((c) => c.sha256)).size;
    if (distinct > 1) moved += 1;
    else flat.push({ group: k, values: list.map((c) => c[axis]), sha256: list[0].sha256 });
    if (new Set(list.map((c) => JSON.stringify(c.rect || null))).size > 1) geometryMoved += 1;
  }
  const values = [...new Set(cells.map((c) => c[axis]))];
  /**
   * PIXEL MOVEMENT ALONE IS NOT PROOF AN AXIS WORKS, and the first live run of this file
   * proved it on itself. `--states normal,maximized` came back `partial` — 3 of 8 groups
   * differed — and read like a working axis. It is not: the matrix drives no maximize
   * control at all. The three that "moved" were Flashcards and one Dictionary/Liquid cell
   * whose CONTENT drifted between the two passes, and the giveaway is geometric — a
   * maximize necessarily changes the window's rect, and all 8 groups had a byte-identical
   * rect (820px wide in every single cell). So an axis is scored on two independent
   * signals, and an axis that moves pixels in only some groups is `partial`, which is a
   * certification BLOCKER rather than a pass: coverage along that dimension is not
   * uniform, and incidental drift is exactly what would let a dead axis dodge
   * `decorative`.
   */
  return {
    axis,
    declaredValues: values,
    comparableGroups: comparable,
    groupsWhereItMoved: moved,
    groupsWhereItMovedNothing: comparable - moved,
    groupsWhereGeometryMoved: geometryMoved,
    flatExamples: flat.slice(0, 4),
    // An axis with only one declared value is not decorative, it is simply not swept.
    verdict: values.length < 2 ? 'not-swept'
      : comparable === 0 ? 'unfalsified'
        : moved === 0 ? 'decorative'
          : moved === comparable ? 'effective'
            : 'partial',
  };
}

/** Check (C). Re-hash every indexed file from disk; never trust the manifest's own claim. */
function integrity(cells) {
  let verified = 0; let missing = 0; let mismatch = 0;
  const mismatches = [];
  for (const c of cells) {
    if (!c.ok || !c.file || !c.sha256) continue;
    const abs = path.join(REPO, c.file);
    if (!fs.existsSync(abs)) { missing += 1; continue; }
    const sha = crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex');
    if (sha === c.sha256) verified += 1;
    else { mismatch += 1; mismatches.push({ file: c.file, indexed: c.sha256, onDisk: sha }); }
  }
  return {
    verified,
    missing,
    mismatch,
    mismatches: mismatches.slice(0, 8),
    // Honest naming: images cleaned out of a gitignored directory is the EXPECTED steady
    // state, not a defect. It only means this atlas cannot be re-viewed, and the sha256s
    // are still checkable against any future run.
    state: mismatch > 0 ? 'CORRUPT' : missing === 0 ? 'all-present'
      : verified === 0 ? 'images-cleaned' : 'partial',
  };
}

/**
 * A CELL THAT COULD NOT EXIST IS NOT A CELL THAT FAILED, and conflating them cost this
 * file its second false blocker. The full-universe run reported "9 cells failed to
 * capture" and refused to certify; all nine are `city`, `musicwidget` and `visualizer` in
 * the Liquid presentation, and the manifest already says why in its own words — those
 * three windows offer no presentation toggle at all. Blocking certification on them is
 * demanding a photograph of something the product does not have.
 *
 * So a non-captured cell is classified from the manifest's OWN record, never from a guess:
 * the app is marked `presentable: false` and the cell asks for a non-default presentation
 * => `unavailable`, a PRODUCT gap that is named by surface and does not block. Anything
 * else is `failed`, an instrument or run problem, and does block.
 *
 * The product gap is not swept under the rug by that: it is reported as its own number
 * with the surfaces listed, which is more visible than being one of nine anonymous
 * failures.
 */
/**
 * THE SAME DEFECT ON THE STATE AXIS, found the moment the state axis was actually merged
 * in: 4 of the 5 "failed" cells are `note` at `maximized`, and the manifest's own error
 * says the reason — a frameless sticky note has no maximize control to drive. That is the
 * identical product gap as `presentable: false`, one axis over.
 *
 * It is matched on the harness's own emitted shape rather than on a per-app flag ONLY
 * because the harness records no `maximizable` field; the reason still comes from the
 * manifest, never from this file's guess. The pattern is deliberately narrow — it demands
 * the harness's exact "surface has no <thing> control of its own" clause — so that a real
 * capture failure (`Error: UnknownVizError`, the compositor flake on `agent`) cannot be
 * laundered into `unavailable`. That cell staying `failed` is this rule's negative control.
 */
const STATE_UNAVAILABLE = /^state [^:]+: surface has no [^:]*control of its own\b/i;

function classify(cell, manifest) {
  if (cell.ok) return 'captured';
  const app = (manifest.apps || {})[cell.app] || {};
  const dflt = ((manifest.dimensions || {}).presentations || ['standard'])[0];
  if (app.opened && app.presentable === false && cell.presentation !== dflt) return 'unavailable';
  if (app.opened && STATE_UNAVAILABLE.test(cell.error || '')) return 'unavailable';
  return 'failed';
}

/** Check (A). Cartesian product from the manifest's own declared dimensions. */
function coverage(manifest) {
  const d = manifest.dimensions || {};
  const apps = d.apps || [];
  const themes = d.themes || [];
  const pres = d.presentations || [];
  const states = d.states || [];
  const declared = apps.length * themes.length * pres.length * states.length;
  const seen = new Set();
  for (const c of manifest.cells || []) {
    seen.add([c.app, c.theme, c.presentation, c.state].join('\u0000'));
  }
  const absent = [];
  for (const a of apps) {
    for (const t of themes) {
      for (const p of pres) {
        for (const s of states) {
          if (!seen.has([a, t, p, s].join('\u0000'))) absent.push({ app: a, theme: t, presentation: p, state: s });
        }
      }
    }
  }
  const cells = manifest.cells || [];
  const captured = cells.filter((c) => c.ok).length;
  const unavailable = cells.filter((c) => classify(c, manifest) === 'unavailable');
  const failed = cells.filter((c) => classify(c, manifest) === 'failed');
  const openedApps = Object.entries(manifest.apps || {})
    .filter(([, v]) => v.opened).map(([k]) => k);
  const canonical = d.canonicalSections || null;
  const attainable = declared - unavailable.length;
  return {
    declaredCells: declared,
    presentCells: cells.length,
    capturedCells: captured,
    failedCells: failed.length,
    unavailableCells: unavailable.length,
    // The product gap, named. These surfaces have NO Liquid presentation to photograph.
    unavailableSurfaces: [...new Set(unavailable.map((c) => c.app))],
    unavailableReason: unavailable.length ? (unavailable[0].error || null) : null,
    /**
     * Once the state axis merged in there are TWO kinds of product gap (no presentation
     * toggle, no maximize control) and one `unavailableReason` string silently described
     * both by the first one it happened to meet. Grouped, so each gap is named with the
     * surfaces it actually applies to.
     */
    unavailableByReason: Object.entries(
      unavailable.reduce((acc, c) => {
        const why = c.error || 'no reason recorded';
        (acc[why] = acc[why] || new Set()).add(c.app);
        return acc;
      }, {}),
    ).map(([reason, apps]) => ({ reason, surfaces: [...apps], cells: unavailable.filter((c) => (c.error || 'no reason recorded') === reason).length })),
    attainableCells: attainable,
    attainableCompleteness: attainable ? +((100 * captured) / attainable).toFixed(2) : 0,
    neverAttempted: absent.length,
    neverAttemptedExamples: absent.slice(0, 6),
    // A cell can be "present" and still be a failure; an atlas that reports one number
    // for both is the fabrication this repo keeps catching elsewhere.
    completeness: declared ? +((100 * captured) / declared).toFixed(2) : 0,
    appsRequested: apps.length,
    appsOpened: openedApps.length,
    appsPresentable: Object.values(manifest.apps || {}).filter((v) => v.presentable).length,
    canonicalSections: canonical,
    // RULE C: never silently truncated. Named, always.
    sampledOut: manifest.sampledOut || [],
    universeCoverage: canonical ? +((100 * apps.length) / canonical).toFixed(2) : null,
    /**
     * The THEME axis has a universe too, and the matrix only records the skipped APPS.
     * An atlas that names 23 sampled-out sections and stays silent about 10 sampled-out
     * themes is truncating exactly as silently on the other axis — RULE C does not care
     * which axis it is.
     */
    themeCatalog: (d.themeCatalog || []).length || null,
    themesSampledOut: (d.themeCatalog || []).map((t) => t.id).filter((id) => !themes.includes(id)),
    themeUniverseCoverage: (d.themeCatalog || []).length
      ? +((100 * themes.length) / d.themeCatalog.length).toFixed(2) : null,
  };
}

/** Check (D). */
function duplicates(cells) {
  const by = new Map();
  for (const c of cells) {
    if (!c.ok || !c.sha256) continue;
    if (!by.has(c.sha256)) by.set(c.sha256, []);
    by.get(c.sha256).push(c);
  }
  const dupes = [...by.entries()].filter(([, l]) => l.length > 1);
  return {
    distinctImages: by.size,
    duplicateGroups: dupes.length,
    cellsInDuplicateGroups: dupes.reduce((n, [, l]) => n + l.length, 0),
    largestGroup: dupes.reduce((n, [, l]) => Math.max(n, l.length), 0),
    examples: dupes.slice(0, 4).map(([sha, l]) => ({
      sha256: sha.slice(0, 12),
      cells: l.map((c) => `${c.app}/${c.presentation}/${c.theme}/${c.state}`),
    })),
  };
}

const CELL_KEY = (c) => [c.app, c.theme, c.presentation, c.state].join('\u0000');

/**
 * MULTI-MANIFEST ASSEMBLY — why the atlas takes a LIST and not a file.
 *
 * Bullet 1's evidence was never one manifest and structurally cannot be. The matrix is a
 * live instrument driving a real desk, so its axes were swept in separate runs: the full
 * 13-theme sweep at `normal`, a `maximized` run for the state axis, and an oled-black
 * re-capture made after the plate-namespace fix. An assembler that reads ONE of those can
 * never report the state axis as anything but `not-swept`, and it re-hashes stale plates
 * that a later run has already replaced. Both were live findings, not hypotheticals:
 * over the full matrix alone this file reported `state: not-swept` and 21 integrity
 * mismatches whose replacements were sitting in a manifest it could not open.
 *
 * The merge is a UNION OF CELLS WITH LAST-WINS PRECEDENCE, and the two honesty rules that
 * make it safe to trust are:
 *
 *   1. NOTHING DERIVED IS MERGED. Only `cells`, `dimensions` and `apps` are unioned; every
 *      computed number — coverage, axis effectiveness, integrity, duplication — is then
 *      re-derived by `assemble()` from the union. Hand-merging a computed block while its
 *      inputs change underneath is how a merged artifact keeps pre-merge counts and lies.
 *   2. SUPERSESSION IS COUNTED AND NAMED, never silent. A later run replacing an earlier
 *      cell is the whole point, but it is also indistinguishable from an atlas quietly
 *      dropping evidence it found inconvenient, so every replaced coordinate is recorded
 *      with the source that lost it.
 *
 * Certification is CONJUNCTIVE across sources: the merge is certifiable only if every
 * contributing run ran its controls and passed them. One un-controlled manifest in the
 * list voids the atlas rather than being averaged away.
 */
function mergeManifests(loaded) {
  if (loaded.length === 1) return { manifest: loaded[0].manifest, provenance: null };

  const cells = new Map();
  const superseded = [];
  const dims = { apps: [], themes: [], presentations: [], states: [], themeCatalog: [] };
  const apps = {};
  const perSource = [];

  for (const { file, manifest } of loaded) {
    for (const c of manifest.cells || []) {
      const key = CELL_KEY(c);
      const prior = cells.get(key);
      if (prior) {
        superseded.push({
          app: c.app, theme: c.theme, presentation: c.presentation, state: c.state,
          supersededFrom: prior.__source, by: file,
        });
        const idx = perSource.find((s) => s.file === prior.__source);
        if (idx) idx.superseded += 1;
      }
      cells.set(key, { ...c, __source: file });
    }
    const d = manifest.dimensions || {};
    for (const axis of ['apps', 'themes', 'presentations', 'states']) {
      for (const v of d[axis] || []) if (!dims[axis].includes(v)) dims[axis].push(v);
    }
    for (const t of d.themeCatalog || []) {
      if (!dims.themeCatalog.some((x) => x.id === t.id)) dims.themeCatalog.push(t);
    }
    if (d.canonicalSections) dims.canonicalSections = d.canonicalSections;
    for (const [id, v] of Object.entries(manifest.apps || {})) {
      const cur = apps[id] || {};
      // OR, not last-wins: a surface opened in ANY run really was opened, and
      // `presentable` is a property of the product rather than of one run's luck.
      apps[id] = { ...cur, ...v, opened: !!(cur.opened || v.opened), presentable: !!(cur.presentable || v.presentable) };
    }
    perSource.push({
      file,
      runId: manifest.runId || null,
      generatedAt: manifest.generatedAt || null,
      cells: (manifest.cells || []).length,
      // Incremented in place by LATER sources that replace one of this source's cells;
      // surviving = cells - superseded, and it is reported rather than inferred.
      superseded: 0,
      certifiable: !!manifest.certifiable,
      controlsRan: !!manifest.controls,
      caretFrozen: !!manifest.caretFrozen,
      // HOW THE SOURCE RUN ADDRESSED ITS WINDOWS, because the app axis is only as real
      // as that key. A run that resolved windows by TITLE collapsed every empty-title
      // section onto one window (`visualizer`/`musicwidget`/`city` here), so its app rows
      // are fabricated for those surfaces and no amount of re-hashing can tell. Manifests
      // written before `addressing` existed report `unrecorded`, which is not the same as
      // `section` and must not be treated as it.
      addressing: (manifest.addressing && manifest.addressing.mode) || 'unrecorded',
      titleCollisions: manifest.addressing && manifest.addressing.titleCollisions
        ? manifest.addressing.titleCollisions.collisions : null,
    });
  }

  // Controls AND-ed across sources; a key any source failed is failed for the merge.
  const controlKeys = [...new Set(loaded.flatMap(({ manifest }) => Object.keys(manifest.controls || {})))];
  const controls = controlKeys.length ? {} : null;
  for (const k of controlKeys) {
    const passes = loaded
      .map(({ manifest }) => (manifest.controls || {})[k])
      .filter((v) => v !== undefined)
      .map((v) => (v.pass === undefined ? v.identical : v.pass));
    controls[k] = { pass: passes.every(Boolean) };
  }
  const uncontrolled = loaded.filter(({ manifest }) => !manifest.controls).map(({ file }) => file);
  const notCertifiable = loaded.filter(({ manifest }) => !manifest.certifiable).map(({ file }) => file);

  // sampledOut survives the merge only where EVERY source skipped it.
  const sampledOut = (loaded[0].manifest.sampledOut || [])
    .filter((s) => loaded.every(({ manifest }) => (manifest.sampledOut || []).includes(s)));

  const merged = {
    schema: 'l12-visual-matrix/v1',
    generatedAt: loaded.map(({ manifest }) => manifest.generatedAt).filter(Boolean).sort().pop() || null,
    dimensions: dims,
    apps,
    sampledOut,
    cells: [...cells.values()].map(({ __source, ...c }) => c),
    controls: uncontrolled.length ? null : controls,
    certifiable: notCertifiable.length === 0,
    void: notCertifiable.length ? `sources not certifiable on their own controls: ${notCertifiable.join(', ')}` : null,
    caretFrozen: loaded.every(({ manifest }) => manifest.caretFrozen),
    // Weakest source wins: one title-addressed source makes the merged app axis suspect,
    // exactly as one uncontrolled source voids the merged controls.
    addressing: {
      mode: loaded.every(({ manifest }) => (manifest.addressing || {}).mode === 'section')
        ? 'section' : 'mixed-or-unrecorded',
      sources: loaded.map(({ file, manifest }) => ({
        file, mode: (manifest.addressing || {}).mode || 'unrecorded',
      })),
    },
  };

  return {
    manifest: merged,
    provenance: {
      sources: perSource,
      mergedCells: cells.size,
      supersededCells: superseded.length,
      // Named, per rule 2 above. Truncated only in the printed list, never in the count.
      supersededExamples: superseded.slice(0, 12),
      uncontrolledSources: uncontrolled,
      nonCertifiableSources: notCertifiable,
    },
  };
}

function assemble(manifest) {
  const cells = manifest.cells || [];
  const cov = coverage(manifest);
  const axes = AXES.map((a) => axisEffect(cells, a));
  const integ = integrity(cells);
  const dup = duplicates(cells);
  const decorative = axes.filter((a) => a.verdict === 'decorative').map((a) => a.axis);

  /**
   * The verdict is deliberately conjunctive and each clause names itself. An atlas is
   * certification evidence ONLY if the run that produced it was already certifiable on
   * its own controls (C1-C4 in the matrix), nothing is missing, no axis is decorative,
   * and no indexed image was rewritten under it.
   */
  const blockers = [];
  if (!manifest.controls) blockers.push('source run had no controls (--control was not passed) — it is not certification evidence and neither is this atlas');
  else if (!manifest.certifiable) blockers.push(`source run is not certifiable: ${manifest.void || 'a matrix control failed'}`);
  if (cov.neverAttempted > 0) blockers.push(`${cov.neverAttempted} declared cells were never attempted`);
  if (cov.failedCells > 0) blockers.push(`${cov.failedCells} cells failed to capture`);
  /**
   * NOT a blocker, and deliberately not silent either: a surface with no Liquid
   * presentation is a product fact this atlas reports rather than a hole in the atlas.
   * It is a genuine L12 finding and belongs in the risk register, not in a verdict that
   * would be unfixable by any amount of photography.
   */
  const gaps = (cov.unavailableByReason || []).map((g) => `${g.surfaces.length} of ${cov.appsOpened} surfaces `
    + `(${g.surfaces.join(', ')}) — ${g.cells} declared cells cannot exist. `
    + `Reported as a product gap, not an atlas defect: ${g.reason}`);
  for (const a of decorative) blockers.push(`axis '${a}' moved no pixels in any comparable group — it is decorative, so the atlas does not cover that dimension`);
  for (const a of axes.filter((x) => x.verdict === 'partial')) {
    blockers.push(`axis '${a.axis}' moved pixels in only ${a.groupsWhereItMoved} of ${a.comparableGroups} comparable groups`
      + ` (and geometry in ${a.groupsWhereGeometryMoved}) — coverage along that dimension is not uniform, and content drift can pass this test without the axis doing anything`);
  }
  if (integ.mismatch > 0) blockers.push(`${integ.mismatch} indexed images no longer hash to their recorded sha256`);
  /**
   * THE APP AXIS IS ONLY AS REAL AS THE KEY THE SOURCE RUN USED TO ADDRESS A WINDOW, and
   * this atlas certified three runs that had no such key. `l12-visual-matrix.cjs` resolved
   * a window by the text in its title bar; `visualizer`, `musicwidget` and the frameless
   * `city` all render an EMPTY title, so a first-match resolve returned one window for all
   * three and the atlas counted three app rows. Integrity cannot see it — the hashes are
   * of real files that really were captured, just of the wrong window — and neither can
   * axis effectiveness, which compares images and not their labels.
   *
   * So it is asserted from provenance rather than from pixels, and `unrecorded` is treated
   * as failing. A manifest that predates `addressing` genuinely does not know.
   */
  const addr = manifest.addressing || {};
  if (addr.mode !== 'section') {
    const named = (addr.sources || []).filter((s) => s.mode !== 'section').map((s) => `${s.file} (${s.mode})`);
    blockers.push('the app axis is unverifiable: '
      + `${named.length ? named.join(', ') : 'this run'} addressed windows by title, and every `
      + 'section that renders an empty title collapses onto one window under a first-match '
      + 'resolve — re-capture with --address section');
  }

  return {
    schema: 'l12-atlas/v1',
    bullet: 'L12 bullet 4 — final visual atlas',
    generatedAt: new Date().toISOString(),
    source: {
      schema: manifest.schema,
      generatedAt: manifest.generatedAt,
      certifiable: !!manifest.certifiable,
      void: manifest.void || null,
      controls: manifest.controls
        ? Object.fromEntries(Object.entries(manifest.controls).map(([k, v]) => [k, v.pass === undefined ? v.identical : v.pass]))
        : null,
      caretFrozen: manifest.caretFrozen,
      addressing: manifest.addressing || { mode: 'unrecorded' },
    },
    dimensions: manifest.dimensions || {},
    coverage: cov,
    axisEffectiveness: axes,
    integrity: integ,
    duplication: dup,
    certifiable: blockers.length === 0,
    blockers,
    productGaps: gaps,
    // The atlas index itself: one row per cell, sorted so a reader walks app by app.
    plates: cells
      .slice()
      .sort((a, b) => `${a.app}${a.presentation}${a.theme}${a.state}`.localeCompare(`${b.app}${b.presentation}${b.theme}${b.state}`))
      .map((c) => ({
        app: c.app,
        presentation: c.presentation,
        theme: c.theme,
        state: c.state,
        ok: !!c.ok,
        file: c.file || null,
        sha256: c.sha256 || null,
        bytes: c.bytes || 0,
        rect: c.rect || null,
        converged: c.converged === undefined ? null : c.converged,
        themeApplied: c.themeApplied === undefined ? null : c.themeApplied,
        error: c.error || null,
      })),
  };
}

/** The human half. References the PNGs by path relative to the sheet's own directory. */
function contactSheet(atlas, sheetPath) {
  const dir = path.dirname(sheetPath);
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const byApp = new Map();
  for (const p of atlas.plates) {
    if (!byApp.has(p.app)) byApp.set(p.app, []);
    byApp.get(p.app).push(p);
  }
  const rel = (f) => (f ? path.relative(dir, path.join(REPO, f)).replace(/\\/g, '/') : null);
  const sections = [...byApp.entries()].map(([app, plates]) => `
    <h2>${esc(app)} <small>${plates.filter((p) => p.ok).length}/${plates.length} captured</small></h2>
    <div class="grid">${plates.map((p) => `
      <figure class="${p.ok ? '' : 'bad'}">
        ${p.ok && p.file ? `<img loading="lazy" src="${esc(rel(p.file))}" alt="${esc(`${app} ${p.presentation} ${p.theme} ${p.state}`)}">`
    : `<div class="missing">${esc(p.error || 'not captured')}</div>`}
        <figcaption>
          <b>${esc(p.presentation)}</b> · ${esc(p.theme)} · ${esc(p.state)}<br>
          <code>${esc((p.sha256 || '').slice(0, 16))}</code>
          ${p.converged === false ? '<em class="warn">did not converge</em>' : ''}
        </figcaption>
      </figure>`).join('')}</div>`).join('\n');

  return `<!doctype html><meta charset="utf-8"><title>L12 visual atlas</title>
<style>
 body{background:#111;color:#ddd;font:13px/1.5 system-ui,sans-serif;margin:24px}
 h1{font-size:20px} h2{font-size:15px;margin:28px 0 8px;border-bottom:1px solid #333;padding-bottom:4px}
 small{color:#888;font-weight:400}
 .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px}
 figure{margin:0;background:#1a1a1a;border:1px solid #2c2c2c;border-radius:6px;overflow:hidden}
 figure.bad{border-color:#7a2a2a}
 img{width:100%;display:block;background:#000}
 .missing{padding:28px 10px;color:#c66;text-align:center}
 figcaption{padding:6px 8px;color:#aaa;font-size:11px}
 code{color:#6a9} .warn{color:#c93;display:block}
 .verdict{padding:10px 12px;border-radius:6px;margin:12px 0}
 .ok{background:#12301c;border:1px solid #2b6b3f} .no{background:#301414;border:1px solid #7a2a2a}
 ul{margin:6px 0 0 18px;padding:0}
</style>
<h1>L12 visual atlas <small>${esc(atlas.generatedAt)}</small></h1>
<div class="verdict ${atlas.certifiable ? 'ok' : 'no'}">
  <b>${atlas.certifiable ? 'CERTIFIABLE' : 'NOT CERTIFICATION EVIDENCE'}</b>
  ${atlas.blockers.length ? `<ul>${atlas.blockers.map((b) => `<li>${esc(b)}</li>`).join('')}</ul>` : ''}
</div>
${atlas.productGaps.length ? `<div class="verdict no"><b>PRODUCT GAP</b><ul>${atlas.productGaps.map((g) => `<li>${esc(g)}</li>`).join('')}</ul></div>` : ''}
<p>${atlas.coverage.capturedCells}/${atlas.coverage.declaredCells} declared cells captured
 (${atlas.coverage.completeness}%, ${atlas.coverage.attainableCompleteness}% of the
 ${atlas.coverage.attainableCells} that can exist) · ${atlas.duplication.distinctImages} distinct images ·
 images on disk: ${esc(atlas.integrity.state)} (${atlas.integrity.verified} verified,
 ${atlas.integrity.missing} missing)</p>
<p>axes: ${atlas.axisEffectiveness.map((a) => `${esc(a.axis)}=<b>${esc(a.verdict)}</b>`).join(' · ')}</p>
<p>apps sampled out (${atlas.coverage.sampledOut.length}): ${esc(atlas.coverage.sampledOut.join(', ') || 'none')}</p>
<p>themes sampled out (${atlas.coverage.themesSampledOut.length}): ${esc(atlas.coverage.themesSampledOut.join(', ') || 'none')}</p>
${sections}
`;
}

// ---------------------------------------------------------------------------------
// Mutation controls. Each damages a deep copy and asserts the matching check reports it.
// ---------------------------------------------------------------------------------
function runControls(manifest, base) {
  const clone = () => JSON.parse(JSON.stringify(manifest));
  const out = {};

  // M1 — drop one cell.
  const m1src = clone();
  if (m1src.cells.length) {
    const dropped = m1src.cells.pop();
    const a = assemble(m1src);
    out.m1 = {
      kind: 'drop-one-cell/coverage-must-report-a-gap',
      dropped: `${dropped.app}/${dropped.presentation}/${dropped.theme}/${dropped.state}`,
      baseNeverAttempted: base.coverage.neverAttempted,
      mutatedNeverAttempted: a.coverage.neverAttempted,
      pass: a.coverage.neverAttempted === base.coverage.neverAttempted + 1,
    };
  } else out.m1 = { kind: 'drop-one-cell', pass: null, note: 'n/a — no cells' };

  // M2 — flatten the sha256 of every cell so the chosen axis moves nothing. The axis
  // picked is whichever one the real run reported EFFECTIVE, so the control attacks a
  // check that was actually passing rather than one already failing.
  const live = base.axisEffectiveness.find((a) => a.verdict === 'effective');
  if (live) {
    const m2src = clone();
    for (const c of m2src.cells) if (c.ok) c.sha256 = 'f'.repeat(64);
    const a = assemble(m2src);
    const after = a.axisEffectiveness.find((x) => x.axis === live.axis);
    out.m2 = {
      kind: 'flatten-images/axis-must-be-reported-decorative',
      axis: live.axis,
      baseVerdict: live.verdict,
      mutatedVerdict: after.verdict,
      pass: after.verdict === 'decorative',
    };
  } else out.m2 = { kind: 'flatten-images', pass: null, note: 'n/a — no axis was effective in the source run, so there is nothing to break' };

  // M3 — corrupt one indexed sha256. Only meaningful while the PNG is on disk.
  const onDisk = (manifest.cells || []).find((c) => c.ok && c.file && fs.existsSync(path.join(REPO, c.file)));
  if (onDisk) {
    const m3src = clone();
    const target = m3src.cells.find((c) => c.file === onDisk.file);
    target.sha256 = `0${target.sha256.slice(1)}`;
    const a = assemble(m3src);
    out.m3 = {
      kind: 'corrupt-one-sha/integrity-must-report-mismatch',
      file: onDisk.file,
      baseMismatch: base.integrity.mismatch,
      mutatedMismatch: a.integrity.mismatch,
      pass: a.integrity.mismatch === base.integrity.mismatch + 1,
    };
  } else {
    out.m3 = {
      kind: 'corrupt-one-sha',
      pass: null,
      note: 'n/a — no indexed PNG is on disk (debug/ is gitignored and gets cleaned), so integrity cannot be falsified in this run',
    };
  }

  // M4 — remove an entire app's cells.
  const apps = [...new Set((manifest.cells || []).map((c) => c.app))];
  if (apps.length > 1) {
    const victim = apps[0];
    const m4src = clone();
    m4src.cells = m4src.cells.filter((c) => c.app !== victim);
    const a = assemble(m4src);
    const lost = base.coverage.capturedCells - a.coverage.capturedCells;
    const expected = (manifest.cells || []).filter((c) => c.app === victim && c.ok).length;
    out.m4 = {
      kind: 'drop-one-app/coverage-must-fall-by-exactly-that-app',
      app: victim,
      expectedLoss: expected,
      observedLoss: lost,
      pass: lost === expected && expected > 0,
    };
  } else out.m4 = { kind: 'drop-one-app', pass: null, note: `n/a — only ${apps.length} app in the run` };

  const fired = Object.values(out).filter((c) => c.pass === true).length;
  const failed = Object.values(out).filter((c) => c.pass === false).length;
  return { ...out, summary: { fired, failed, notApplicable: 4 - fired - failed } };
}

// ---------------------------------------------------------------------------------
(() => {
  // Comma-separated, and ORDER IS PRECEDENCE: a later manifest supersedes an earlier one
  // on the same cell coordinate. One path behaves exactly as before.
  const requested = arg('manifest', path.join('debug', 'l12-matrix-manifest.json'))
    .split(',').map((s) => s.trim()).filter(Boolean);
  const loaded = [];
  for (const rel of requested) {
    const manifestPath = path.resolve(REPO, rel);
    if (!fs.existsSync(manifestPath)) {
      console.error(`REFUSE - no matrix manifest at ${manifestPath}. Run l12-visual-matrix.cjs first.`);
      process.exit(2);
    }
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    if (manifest.schema !== 'l12-visual-matrix/v1') {
      console.error(`REFUSE - ${manifestPath} is schema '${manifest.schema}', not l12-visual-matrix/v1`);
      process.exit(2);
    }
    loaded.push({ file: path.relative(REPO, manifestPath).replace(/\\/g, '/'), manifest });
  }

  const { manifest, provenance } = mergeManifests(loaded);
  const atlas = assemble(manifest);
  atlas.sourceManifest = loaded.map((l) => l.file).join(',');
  atlas.multiRun = provenance;
  if (has('control')) atlas.mutationControls = runControls(manifest, atlas);
  else atlas.mutationControls = null;

  const sheetPath = path.resolve(REPO, arg('sheet', path.join('debug', 'shots', 'l12-atlas.html')));
  fs.mkdirSync(path.dirname(sheetPath), { recursive: true });
  fs.writeFileSync(sheetPath, contactSheet(atlas, sheetPath));
  atlas.contactSheet = path.relative(REPO, sheetPath).replace(/\\/g, '/');

  const outPath = path.resolve(REPO, arg('out', path.join('src', '.coordination', 'liquid-workplace', 'baselines', 'l12-atlas.json')));
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, `${JSON.stringify(atlas, null, 2)}\n`);

  console.log(JSON.stringify({
    out: path.relative(REPO, outPath).replace(/\\/g, '/'),
    sheet: atlas.contactSheet,
    plates: atlas.plates.length,
    coverage: atlas.coverage,
    axes: Object.fromEntries(atlas.axisEffectiveness.map((a) => [a.axis, a.verdict])),
    integrity: atlas.integrity.state,
    distinctImages: atlas.duplication.distinctImages,
    certifiable: atlas.certifiable,
    blockers: atlas.blockers,
    productGaps: atlas.productGaps,
    controls: atlas.mutationControls && atlas.mutationControls.summary,
  }, null, 2));
  process.exit(atlas.certifiable ? 0 : 1);
})();
