/**
 * L12 BULLET 4, first half — THE FINAL VISUAL ATLAS.
 *
 * This assembles an atlas from an `l12-visual-matrix/v1` manifest: a coverage-accounted
 * index of every captured cell, a human-viewable contact sheet, and a verdict on whether
 * the run may be called certification evidence at all.
 *
 * WHY IT IS A SEPARATE MODULE FROM THE HARNESS THAT PRODUCES THE MANIFEST, decided here
 * and recorded so it is not "tidied" back:
 *
 *   1. `l12-visual-matrix.cjs` REFUSES without `debug/bridge.json` — it is a live
 *      instrument. An atlas welded into it could only ever be regenerated by re-running
 *      the whole matrix against a running app. The release handoff's atlas has to be
 *      rebuildable from BANKED evidence, years after the app that produced it stopped
 *      running, so the assembler takes a file and touches no bridge.
 *   2. Bullet 1 (the matrix) and bullet 4 (the atlas) have different owners working
 *      concurrently in different trees. Two workers editing one 750-line file is how work
 *      is lost here.
 *
 * The harness's reserved `--atlas` flag stays meaningful: it shells out to this file after
 * a run, so the flag is a pass-through rather than a second implementation.
 *
 * ---------------------------------------------------------------------------------
 * WHAT AN ATLAS CAN LIE ABOUT, AND THE FOUR CHECKS THAT STOP IT.
 *
 * A wall of 182 screenshots is the single most convincing artifact this plan can produce
 * and it proves nothing by itself. Every failure below is one this repo has already
 * committed at least once in some other instrument.
 *
 * (A) COVERAGE THAT IS ASSERTED RATHER THAN COUNTED. The atlas recomputes the full
 *     cartesian product |apps| x |themes| x |presentations| x |states| from the
 *     manifest's OWN declared dimensions and subtracts what is actually present. A cell
 *     that was never attempted and a cell that failed are different numbers and are
 *     reported as different numbers. `sampledOut` sections are listed BY NAME (RULE C
 *     forbids silent truncation) and the atlas states its coverage of the canonical
 *     section universe, not just of what was requested.
 *
 * (B) A DECORATIVE AXIS. This is the C4 defect one level up. The matrix's first draft
 *     captured the whole renderer, so the "app" axis moved no pixels and the run still
 *     looked complete; a `rect` crop fixed it and control C4 keeps it honest. The atlas
 *     applies the same question to EVERY axis mechanically: hold three axes fixed, vary
 *     the fourth, and count how many DISTINCT sha256s come back. An axis whose every
 *     comparable group returns exactly one distinct image moved nothing, and an atlas
 *     built on it is claiming a dimension of coverage it does not have. That axis is
 *     reported `decorative` and the atlas is NOT certifiable.
 *
 *     Live finding this check was written against, and it fired on its first run: the
 *     matrix accepts `--states normal,maximized` in its own usage line but the state
 *     loop drives nothing -- no code reaches a maximize control -- so two passes would
 *     bank identical images under two labels. Reported, not silently repaired: that file
 *     belongs to bullet 1 and to another worker.
 *
 * (C) BYTES THAT ARE NOT THERE. `debug/` is gitignored, so the PNGs an atlas indexes are
 *     deleted the moment anyone cleans the tree, while the JSON keeps asserting they
 *     exist at a given size and hash. Every cell is therefore re-hashed FROM DISK at
 *     assembly time and lands in one of three honest states -- `verified` (present and
 *     the hash matches), `missing` (indexed but not on disk), `mismatch` (present and the
 *     hash does NOT match, which means something rewrote it). An atlas whose images are
 *     all `missing` is still a legitimate artifact -- the sha256s remain checkable
 *     against any future re-run -- but it says so in its own verdict instead of implying
 *     a picture wall that no longer exists.
 *
 * (D) DUPLICATES PASSED OFF AS COVERAGE. Cells sharing one sha256 are grouped and counted.
 *     Some duplication is legitimate (an app with no Liquid toggle photographs identically
 *     in both presentations, and the manifest says why); duplication ACROSS a must-differ
 *     axis is check (B). The raw number is published either way.
 *
 * ---------------------------------------------------------------------------------
 * THE MUTATION CONTROL, `--control`. Four checks that all pass on good input tell you
 * nothing about whether they can fail. Each control below damages an in-memory COPY of
 * the manifest in one specific way and asserts the corresponding check reports it:
 *
 *   M1  drop one cell            -> coverage must report exactly one more missing cell
 *   M2  flatten one axis's shas  -> that axis must be reported decorative
 *   M3  corrupt one sha256       -> integrity must report a mismatch (needs the PNG on
 *                                   disk; with the images cleaned it reports `n/a`
 *                                   rather than a pass it did not earn)
 *   M4  drop a whole app's cells -> app coverage must fall by exactly that app
 *
 * A control that cannot run says `n/a` with its reason. It never scores a pass.
 *
 * ---------------------------------------------------------------------------------
 * TWO ADDITIONS MADE WHEN BULLET 1 CLOSED (2026-09-02), both forced by what its final
 * evidence actually looks like, neither optional:
 *
 * (1) `--manifest a.json,b.json` — MORE THAN ONE SOURCE RUN. Bullet 1 did not close as one
 *     manifest and could not have: the state axis needs a maximized pass, and sweeping
 *     25 apps x 13 themes x 2 presentations x 2 states is 1,300 cells of Electron driving.
 *     It closed as a 650-cell `normal` run over all 13 themes plus a 100-cell `maximized`
 *     run over the two extreme ones. An atlas that could only read one of those would have
 *     to declare the state axis `not-swept` while the evidence for it sits on disk.
 *
 *     COVERAGE IS STILL COMPUTED PER SOURCE RUN, and that is the whole subtlety. Taking the
 *     union of the declared dimensions instead would fabricate a 1,300-cell universe that
 *     nobody ever intended to capture and then report 599 cells "never attempted" — a
 *     blocker invented by the atlas out of its own arithmetic. Each run is scored against
 *     the cartesian product IT declared; the aggregate is the sum, not a cross-product.
 *     Only axis effectiveness, integrity and duplication read the merged cell set, because
 *     those three ask questions about images and are indifferent to which run banked them.
 *
 * (2) `--shots-root <dir>` — the PNGs need not live under this checkout. Bullet 1 ran in the
 *     main tree and its 710 plates are in that tree's gitignored `debug/shots/`; this file
 *     runs from a worktree. Copying 59 MB of PNGs across to re-hash them would be the
 *     wrong fix twice over — the disk is nearly full, and an atlas that can only verify
 *     images sitting in its own checkout is exactly the un-rebuildable artifact the
 *     separate-module decision above was made to avoid.
 *
 * ---------------------------------------------------------------------------------
 * Run:
 *   node src/.coordination/liquid-workplace/probes/l12-atlas.cjs \
 *     [--manifest a.json[,b.json...]] [--shots-root <dir>] [--out <atlas.json>] \
 *     [--sheet debug/shots/l12-atlas.html] [--control]
 *
 * WHAT IS COMMITTED: the atlas JSON only. The contact sheet is HTML that references
 * gitignored PNGs by relative path, so it lands in `debug/shots/` beside them.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const REPO = path.join(__dirname, '..', '..', '..', '..');
const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : dflt;
};
const has = (name) => process.argv.indexOf(`--${name}`) >= 0;
/** Where a cell's `file` path is rooted. Defaults to this checkout; see addition (2) above. */
const SHOTS_ROOT = path.resolve(REPO, arg('shots-root', REPO));

const AXES = ['app', 'theme', 'presentation', 'state'];

/** The identity of a cell: one photograph of one app in one configuration. */
const cellKey = (c) => JSON.stringify([c.app, c.theme, c.presentation, c.state]);

/** The key of a cell with one axis removed — the group inside which that axis varies. */
function groupKey(cell, without) {
  return AXES.filter((a) => a !== without).map((a) => `${a}=${cell[a]}`).join('|');
}

/**
 * Check (B). For one axis: partition the captured cells by everything EXCEPT that axis,
 * and inside each partition count distinct images. A partition with a single member
 * cannot falsify anything and is excluded from the verdict rather than counted as a pass.
 */
function axisEffect(cells, axis) {
  const groups = new Map();
  for (const c of cells) {
    if (!c.ok || !c.sha256) continue;
    const k = groupKey(c, axis);
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(c);
  }
  let comparable = 0;
  let moved = 0;
  let geometryMoved = 0;
  const flat = [];
  for (const [k, list] of groups) {
    if (list.length < 2) continue;
    comparable += 1;
    const distinct = new Set(list.map((c) => c.sha256)).size;
    if (distinct > 1) moved += 1;
    else flat.push({ group: k, values: list.map((c) => c[axis]), sha256: list[0].sha256 });
    if (new Set(list.map((c) => JSON.stringify(c.rect || null))).size > 1) geometryMoved += 1;
  }
  const values = [...new Set(cells.map((c) => c[axis]))];
  /**
   * PIXEL MOVEMENT ALONE IS NOT PROOF AN AXIS WORKS, and the first live run of this file
   * proved it on itself. `--states normal,maximized` came back `partial` — 3 of 8 groups
   * differed — and read like a working axis. It is not: the matrix drives no maximize
   * control at all. The three that "moved" were Flashcards and one Dictionary/Liquid cell
   * whose CONTENT drifted between the two passes, and the giveaway is geometric — a
   * maximize necessarily changes the window's rect, and all 8 groups had a byte-identical
   * rect (820px wide in every single cell). So an axis is scored on two independent
   * signals, and an axis that moves pixels in only some groups is `partial`, which is a
   * certification BLOCKER rather than a pass: coverage along that dimension is not
   * uniform, and incidental drift is exactly what would let a dead axis dodge
   * `decorative`.
   */
  return {
    axis,
    declaredValues: values,
    comparableGroups: comparable,
    groupsWhereItMoved: moved,
    groupsWhereItMovedNothing: comparable - moved,
    groupsWhereGeometryMoved: geometryMoved,
    flatExamples: flat.slice(0, 4),
    // An axis with only one declared value is not decorative, it is simply not swept.
    verdict: values.length < 2 ? 'not-swept'
      : comparable === 0 ? 'unfalsified'
        : moved === 0 ? 'decorative'
          : moved === comparable ? 'effective'
            : 'partial',
  };
}

/** Check (C). Re-hash every indexed file from disk; never trust the manifest's own claim. */
function integrity(cells) {
  let verified = 0; let missing = 0; let mismatch = 0;
  const mismatches = [];
  for (const c of cells) {
    if (!c.ok || !c.file || !c.sha256) continue;
    const abs = path.join(SHOTS_ROOT, c.file);
    if (!fs.existsSync(abs)) { missing += 1; continue; }
    const sha = crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex');
    if (sha === c.sha256) verified += 1;
    else { mismatch += 1; mismatches.push({ file: c.file, indexed: c.sha256, onDisk: sha }); }
  }
  return {
    verified,
    missing,
    mismatch,
    mismatches: mismatches.slice(0, 8),
    // Honest naming: images cleaned out of a gitignored directory is the EXPECTED steady
    // state, not a defect. It only means this atlas cannot be re-viewed, and the sha256s
    // are still checkable against any future run.
    state: mismatch > 0 ? 'CORRUPT' : missing === 0 ? 'all-present'
      : verified === 0 ? 'images-cleaned' : 'partial',
  };
}

/**
 * A CELL THAT COULD NOT EXIST IS NOT A CELL THAT FAILED, and conflating them cost this
 * file its second false blocker. The full-universe run reported "9 cells failed to
 * capture" and refused to certify; all nine are `city`, `musicwidget` and `visualizer` in
 * the Liquid presentation, and the manifest already says why in its own words — those
 * three windows offer no presentation toggle at all. Blocking certification on them is
 * demanding a photograph of something the product does not have.
 *
 * So a non-captured cell is classified from the manifest's OWN record, never from a guess:
 * the app is marked `presentable: false` and the cell asks for a non-default presentation
 * => `unavailable`, a PRODUCT gap that is named by surface and does not block. Anything
 * else is `failed`, an instrument or run problem, and does block.
 *
 * The product gap is not swept under the rug by that: it is reported as its own number
 * with the surfaces listed, which is more visible than being one of nine anonymous
 * failures.
 */
/**
 * WHICH SURFACE/AXIS-VALUE PAIRS THE PRODUCT SIMPLY DOES NOT OFFER, derived mechanically
 * from the manifest's own per-cell booleans and NEVER from its prose.
 *
 * The first version of this only understood the PRESENTATION axis, via the app summary's
 * `presentable` flag, and the state axis caught it out the moment bullet 1 actually swept
 * one: the maximized run's four `note` cells came back `stateReached: false` because a
 * frameless sticky note has no maximize control, and the atlas called them capture
 * FAILURES and refused to certify — the same false blocker as the nine Liquid cells one
 * revision earlier, one axis over. Generalising is the fix; special-casing `note` would
 * only move the bug to the next surface.
 *
 * The test is a property of the SURFACE, not of one attempt: for a given (app, axis value)
 * the axis must have gone unreached in EVERY cell that asked for it, and there must be at
 * least two such cells. One flake among four attempts stays `failed`, which is what
 * separates "this control does not exist" from "this click did not land" without reading a
 * single error string. The reason is then quoted VERBATIM from the manifest's own record.
 */
function unavailability(manifest) {
  const reachedField = { presentation: 'presentationReached', state: 'stateReached' };
  const map = new Map();
  for (const axis of ['presentation', 'state']) {
    const groups = new Map();
    for (const c of manifest.cells || []) {
      const k = JSON.stringify([c.app, c[axis]]);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k).push(c);
    }
    for (const list of groups.values()) {
      if (list.length < 2) continue;
      if (!list.every((c) => c[reachedField[axis]] === false)) continue;
      map.set(JSON.stringify([axis, list[0].app, list[0][axis]]), {
        axis,
        app: list[0].app,
        value: list[0][axis],
        cells: list.length,
        reason: list[0].error || null,
      });
    }
  }
  return map;
}

function classify(cell, manifest, unav) {
  if (cell.ok) return 'captured';
  const u = unav || unavailability(manifest);
  for (const axis of ['presentation', 'state']) {
    if (u.has(JSON.stringify([axis, cell.app, cell[axis]]))) return 'unavailable';
  }
  return 'failed';
}

/** Check (A). Cartesian product from the manifest's own declared dimensions. */
function coverage(manifest) {
  const d = manifest.dimensions || {};
  const apps = d.apps || [];
  const themes = d.themes || [];
  const pres = d.presentations || [];
  const states = d.states || [];
  const declared = apps.length * themes.length * pres.length * states.length;
  const seen = new Set();
  for (const c of manifest.cells || []) {
    seen.add(cellKey(c));
  }
  const absent = [];
  for (const a of apps) {
    for (const t of themes) {
      for (const p of pres) {
        for (const s of states) {
          if (!seen.has(cellKey({ app: a, theme: t, presentation: p, state: s }))) absent.push({ app: a, theme: t, presentation: p, state: s });
        }
      }
    }
  }
  const cells = manifest.cells || [];
  const captured = cells.filter((c) => c.ok).length;
  const unav = unavailability(manifest);
  const unavailable = cells.filter((c) => classify(c, manifest, unav) === 'unavailable');
  const failed = cells.filter((c) => classify(c, manifest, unav) === 'failed');
  const openedApps = Object.entries(manifest.apps || {})
    .filter(([, v]) => v.opened).map(([k]) => k);
  const canonical = d.canonicalSections || null;
  const attainable = declared - unavailable.length;
  return {
    declaredCells: declared,
    presentCells: cells.length,
    capturedCells: captured,
    failedCells: failed.length,
    unavailableCells: unavailable.length,
    // The product gap, named. These surfaces have NO Liquid presentation to photograph.
    unavailableSurfaces: [...new Set(unavailable.map((c) => c.app))],
    unavailableReason: unavailable.length ? (unavailable[0].error || null) : null,
    // Per-axis, because a surface with no maximize control and a surface with no Liquid
    // toggle are two different product gaps and were being reported as one number.
    unavailableByAxis: [...unav.values()].map((u) => ({
      axis: u.axis, app: u.app, value: u.value, cells: u.cells, reason: u.reason,
    })),
    attainableCells: attainable,
    attainableCompleteness: attainable ? +((100 * captured) / attainable).toFixed(2) : 0,
    neverAttempted: absent.length,
    neverAttemptedExamples: absent.slice(0, 6),
    // A cell can be "present" and still be a failure; an atlas that reports one number
    // for both is the fabrication this repo keeps catching elsewhere.
    completeness: declared ? +((100 * captured) / declared).toFixed(2) : 0,
    appsRequested: apps.length,
    appsOpened: openedApps.length,
    appsPresentable: Object.values(manifest.apps || {}).filter((v) => v.presentable).length,
    canonicalSections: canonical,
    // RULE C: never silently truncated. Named, always.
    sampledOut: manifest.sampledOut || [],
    universeCoverage: canonical ? +((100 * apps.length) / canonical).toFixed(2) : null,
    /**
     * The THEME axis has a universe too, and the matrix only records the skipped APPS.
     * An atlas that names 23 sampled-out sections and stays silent about 10 sampled-out
     * themes is truncating exactly as silently on the other axis — RULE C does not care
     * which axis it is.
     */
    themeCatalog: (d.themeCatalog || []).length || null,
    themesSampledOut: (d.themeCatalog || []).map((t) => t.id).filter((id) => !themes.includes(id)),
    themeUniverseCoverage: (d.themeCatalog || []).length
      ? +((100 * themes.length) / d.themeCatalog.length).toFixed(2) : null,
  };
}

/**
 * MERGING SOURCE RUNS. See addition (1) in the header for why coverage is deliberately NOT
 * merged. What IS merged is the cell set — the photographs — because integrity, duplication
 * and axis effectiveness are questions about images and do not care which run banked them.
 *
 * A collision (two runs claiming the same app/theme/presentation/state) is the one thing
 * that could silently corrupt this: whichever manifest was listed last would shadow the
 * other and the atlas would index a picture it never accounted for. Collisions are counted
 * and named, the FIRST occurrence wins, and a collision is a certification blocker — two
 * runs disagreeing about one cell means at least one of them is stale.
 */
function mergeSources(manifests) {
  const byKey = new Map();
  const collisions = [];
  for (const m of manifests) {
    for (const c of m.cells || []) {
      const k = cellKey(c);
      if (byKey.has(k)) { collisions.push({ cell: `${c.app}/${c.presentation}/${c.theme}/${c.state}`, from: m.__file }); continue; }
      byKey.set(k, { ...c, __from: m.__file });
    }
  }
  const apps = {};
  for (const m of manifests) for (const [k, v] of Object.entries(m.apps || {})) if (!apps[k]) apps[k] = v;
  const union = (sel) => [...new Set(manifests.flatMap((m) => (m.dimensions || {})[sel] || []))];
  return {
    cells: [...byKey.values()],
    apps,
    collisions,
    dimensions: {
      apps: union('apps'),
      themes: union('themes'),
      presentations: union('presentations'),
      states: union('states'),
      canonicalSections: (manifests[0].dimensions || {}).canonicalSections || null,
      themeCatalog: (manifests.find((m) => ((m.dimensions || {}).themeCatalog || []).length) || { dimensions: {} }).dimensions.themeCatalog || [],
    },
  };
}

/**
 * The aggregate of the per-run coverages. Sums, never a cross-product: three runs of 10
 * cells each cover 30 cells, not 1,000. Rates are recomputed from the summed numerators
 * and denominators rather than averaged, because averaging percentages over runs of
 * different sizes is its own small fabrication.
 */
function aggregateCoverage(perSource, merged) {
  const sum = (f) => perSource.reduce((n, s) => n + (f(s) || 0), 0);
  const declared = sum((s) => s.coverage.declaredCells);
  const captured = sum((s) => s.coverage.capturedCells);
  const unavailable = sum((s) => s.coverage.unavailableCells);
  const attainable = declared - unavailable;
  const d = merged.dimensions;
  const canonical = d.canonicalSections || null;
  const surfaces = [...new Set(perSource.flatMap((s) => s.coverage.unavailableSurfaces))];
  const openedApps = Object.entries(merged.apps).filter(([, v]) => v.opened).map(([k]) => k);
  return {
    declaredCells: declared,
    presentCells: sum((s) => s.coverage.presentCells),
    capturedCells: captured,
    failedCells: sum((s) => s.coverage.failedCells),
    unavailableCells: unavailable,
    unavailableSurfaces: surfaces,
    unavailableReason: (perSource.find((s) => s.coverage.unavailableReason) || { coverage: {} }).coverage.unavailableReason || null,
    attainableCells: attainable,
    attainableCompleteness: attainable ? +((100 * captured) / attainable).toFixed(2) : 0,
    neverAttempted: sum((s) => s.coverage.neverAttempted),
    neverAttemptedExamples: perSource.flatMap((s) => s.coverage.neverAttemptedExamples).slice(0, 6),
    completeness: declared ? +((100 * captured) / declared).toFixed(2) : 0,
    // Distinct cells actually indexed, which is what the atlas can show a reader.
    distinctCellsIndexed: merged.cells.length,
    mergeCollisions: merged.collisions.length,
    mergeCollisionExamples: merged.collisions.slice(0, 6),
    appsRequested: d.apps.length,
    appsOpened: openedApps.length,
    appsPresentable: Object.values(merged.apps).filter((v) => v.presentable).length,
    canonicalSections: canonical,
    unavailableByAxis: perSource.flatMap((s) => s.coverage.unavailableByAxis),
    sampledOut: [...new Set(perSource.flatMap((s) => s.coverage.sampledOut))],
    universeCoverage: canonical ? +((100 * d.apps.length) / canonical).toFixed(2) : null,
    themeCatalog: (d.themeCatalog || []).length || null,
    themesSampledOut: (d.themeCatalog || []).map((t) => t.id).filter((id) => !d.themes.includes(id)),
    themeUniverseCoverage: (d.themeCatalog || []).length
      ? +((100 * d.themes.length) / d.themeCatalog.length).toFixed(2) : null,
  };
}

/** Check (D). */
function duplicates(cells) {
  const by = new Map();
  for (const c of cells) {
    if (!c.ok || !c.sha256) continue;
    if (!by.has(c.sha256)) by.set(c.sha256, []);
    by.get(c.sha256).push(c);
  }
  const dupes = [...by.entries()].filter(([, l]) => l.length > 1);
  return {
    distinctImages: by.size,
    duplicateGroups: dupes.length,
    cellsInDuplicateGroups: dupes.reduce((n, [, l]) => n + l.length, 0),
    largestGroup: dupes.reduce((n, [, l]) => Math.max(n, l.length), 0),
    examples: dupes.slice(0, 4).map(([sha, l]) => ({
      sha256: sha.slice(0, 12),
      cells: l.map((c) => `${c.app}/${c.presentation}/${c.theme}/${c.state}`),
    })),
  };
}

function assemble(manifests) {
  const merged = mergeSources(manifests);
  const perSource = manifests.map((m) => ({
    manifest: m.__file,
    generatedAt: m.generatedAt,
    certifiable: !!m.certifiable,
    void: m.void || null,
    hasControls: !!m.controls,
    controls: m.controls
      ? Object.fromEntries(Object.entries(m.controls).map(([k, v]) => [k, v.pass === undefined ? v.identical : v.pass]))
      : null,
    caretFrozen: m.caretFrozen,
    dimensions: m.dimensions || {},
    coverage: coverage(m),
  }));
  const cells = merged.cells;
  const cov = aggregateCoverage(perSource, merged);
  const axes = AXES.map((a) => axisEffect(cells, a));
  const integ = integrity(cells);
  const dup = duplicates(cells);
  const decorative = axes.filter((a) => a.verdict === 'decorative').map((a) => a.axis);

  /**
   * The verdict is deliberately conjunctive and each clause names itself. An atlas is
   * certification evidence ONLY if the run that produced it was already certifiable on
   * its own controls (C1-C4 in the matrix), nothing is missing, no axis is decorative,
   * and no indexed image was rewritten under it.
   */
  const blockers = [];
  for (const s of perSource) {
    if (!s.hasControls) blockers.push(`source run ${s.manifest} had no controls (--control was not passed) — it is not certification evidence and neither is this atlas`);
    else if (!s.certifiable) blockers.push(`source run ${s.manifest} is not certifiable: ${s.void || 'a matrix control failed'}`);
  }
  if (cov.mergeCollisions > 0) {
    blockers.push(`${cov.mergeCollisions} cells are claimed by more than one source run `
      + `(${cov.mergeCollisionExamples.map((c) => c.cell).join(', ')}) — two runs disagreeing about one cell means at least one is stale, and the atlas would be indexing a photograph it did not account for`);
  }
  if (cov.neverAttempted > 0) blockers.push(`${cov.neverAttempted} declared cells were never attempted`);
  if (cov.failedCells > 0) blockers.push(`${cov.failedCells} cells failed to capture`);
  /**
   * NOT a blocker, and deliberately not silent either: a surface with no Liquid
   * presentation is a product fact this atlas reports rather than a hole in the atlas.
   * It is a genuine L12 finding and belongs in the risk register, not in a verdict that
   * would be unfixable by any amount of photography.
   */
  const gaps = [];
  for (const axis of ['presentation', 'state']) {
    const rows = cov.unavailableByAxis.filter((u) => u.axis === axis);
    if (!rows.length) continue;
    const surfaces = [...new Set(rows.map((u) => u.app))];
    gaps.push(`${surfaces.length} of ${cov.appsOpened} surfaces never reach a value on the '${axis}' axis `
      + `(${surfaces.join(', ')}) — ${rows.reduce((n, u) => n + u.cells, 0)} declared cells cannot exist. `
      + `Reported as a product gap, not an atlas defect: ${rows[0].reason}`);
  }
  for (const a of decorative) blockers.push(`axis '${a}' moved no pixels in any comparable group — it is decorative, so the atlas does not cover that dimension`);
  for (const a of axes.filter((x) => x.verdict === 'partial')) {
    blockers.push(`axis '${a.axis}' moved pixels in only ${a.groupsWhereItMoved} of ${a.comparableGroups} comparable groups`
      + ` (and geometry in ${a.groupsWhereGeometryMoved}) — coverage along that dimension is not uniform, and content drift can pass this test without the axis doing anything`);
  }
  if (integ.mismatch > 0) blockers.push(`${integ.mismatch} indexed images no longer hash to their recorded sha256`);

  return {
    schema: 'l12-atlas/v1',
    bullet: 'L12 bullet 4 — final visual atlas',
    generatedAt: new Date().toISOString(),
    // One entry per source run, each carrying the coverage it is scored against. The
    // top-level `coverage` is the sum of these, never a cross-product of their dimensions.
    sources: perSource,
    shotsRoot: SHOTS_ROOT === REPO ? 'this checkout' : SHOTS_ROOT.replace(/\\/g, '/'),
    dimensions: merged.dimensions,
    coverage: cov,
    axisEffectiveness: axes,
    integrity: integ,
    duplication: dup,
    certifiable: blockers.length === 0,
    blockers,
    productGaps: gaps,
    // The atlas index itself: one row per cell, sorted so a reader walks app by app.
    plates: cells
      .slice()
      .sort((a, b) => `${a.app}${a.presentation}${a.theme}${a.state}`.localeCompare(`${b.app}${b.presentation}${b.theme}${b.state}`))
      .map((c) => ({
        app: c.app,
        presentation: c.presentation,
        theme: c.theme,
        state: c.state,
        ok: !!c.ok,
        file: c.file || null,
        sha256: c.sha256 || null,
        bytes: c.bytes || 0,
        rect: c.rect || null,
        converged: c.converged === undefined ? null : c.converged,
        themeApplied: c.themeApplied === undefined ? null : c.themeApplied,
        error: c.error || null,
        // Which source run banked this photograph. With one manifest it is constant; with
        // several it is the only way a reader can trace a plate back to its run.
        from: c.__from || null,
      })),
  };
}

/** The human half. References the PNGs by path relative to the sheet's own directory. */
function contactSheet(atlas, sheetPath) {
  const dir = path.dirname(sheetPath);
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const byApp = new Map();
  for (const p of atlas.plates) {
    if (!byApp.has(p.app)) byApp.set(p.app, []);
    byApp.get(p.app).push(p);
  }
  const rel = (f) => (f ? path.relative(dir, path.join(SHOTS_ROOT, f)).replace(/\\/g, '/') : null);
  const sections = [...byApp.entries()].map(([app, plates]) => `
    <h2>${esc(app)} <small>${plates.filter((p) => p.ok).length}/${plates.length} captured</small></h2>
    <div class="grid">${plates.map((p) => `
      <figure class="${p.ok ? '' : 'bad'}">
        ${p.ok && p.file ? `<img loading="lazy" src="${esc(rel(p.file))}" alt="${esc(`${app} ${p.presentation} ${p.theme} ${p.state}`)}">`
    : `<div class="missing">${esc(p.error || 'not captured')}</div>`}
        <figcaption>
          <b>${esc(p.presentation)}</b> · ${esc(p.theme)} · ${esc(p.state)}<br>
          <code>${esc((p.sha256 || '').slice(0, 16))}</code>
          ${p.converged === false ? '<em class="warn">did not converge</em>' : ''}
        </figcaption>
      </figure>`).join('')}</div>`).join('\n');

  return `<!doctype html><meta charset="utf-8"><title>L12 visual atlas</title>
<style>
 body{background:#111;color:#ddd;font:13px/1.5 system-ui,sans-serif;margin:24px}
 h1{font-size:20px} h2{font-size:15px;margin:28px 0 8px;border-bottom:1px solid #333;padding-bottom:4px}
 small{color:#888;font-weight:400}
 .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px}
 figure{margin:0;background:#1a1a1a;border:1px solid #2c2c2c;border-radius:6px;overflow:hidden}
 figure.bad{border-color:#7a2a2a}
 img{width:100%;display:block;background:#000}
 .missing{padding:28px 10px;color:#c66;text-align:center}
 figcaption{padding:6px 8px;color:#aaa;font-size:11px}
 code{color:#6a9} .warn{color:#c93;display:block}
 .verdict{padding:10px 12px;border-radius:6px;margin:12px 0}
 .ok{background:#12301c;border:1px solid #2b6b3f} .no{background:#301414;border:1px solid #7a2a2a}
 ul{margin:6px 0 0 18px;padding:0}
</style>
<h1>L12 visual atlas <small>${esc(atlas.generatedAt)}</small></h1>
<div class="verdict ${atlas.certifiable ? 'ok' : 'no'}">
  <b>${atlas.certifiable ? 'CERTIFIABLE' : 'NOT CERTIFICATION EVIDENCE'}</b>
  ${atlas.blockers.length ? `<ul>${atlas.blockers.map((b) => `<li>${esc(b)}</li>`).join('')}</ul>` : ''}
</div>
${atlas.productGaps.length ? `<div class="verdict no"><b>PRODUCT GAP</b><ul>${atlas.productGaps.map((g) => `<li>${esc(g)}</li>`).join('')}</ul></div>` : ''}
<p>${atlas.coverage.capturedCells}/${atlas.coverage.declaredCells} declared cells captured
 (${atlas.coverage.completeness}%, ${atlas.coverage.attainableCompleteness}% of the
 ${atlas.coverage.attainableCells} that can exist) · ${atlas.duplication.distinctImages} distinct images ·
 images on disk: ${esc(atlas.integrity.state)} (${atlas.integrity.verified} verified,
 ${atlas.integrity.missing} missing)</p>
<p>axes: ${atlas.axisEffectiveness.map((a) => `${esc(a.axis)}=<b>${esc(a.verdict)}</b>`).join(' · ')}</p>
<p>apps sampled out (${atlas.coverage.sampledOut.length}): ${esc(atlas.coverage.sampledOut.join(', ') || 'none')}</p>
<p>themes sampled out (${atlas.coverage.themesSampledOut.length}): ${esc(atlas.coverage.themesSampledOut.join(', ') || 'none')}</p>
${sections}
`;
}

// ---------------------------------------------------------------------------------
// Mutation controls. Each damages a deep copy and asserts the matching check reports it.
// ---------------------------------------------------------------------------------
function runControls(manifests, base) {
  const clone = () => JSON.parse(JSON.stringify(manifests));
  const allCells = manifests.flatMap((m) => m.cells || []);
  const out = {};

  // M1 — drop one cell.
  const m1src = clone();
  const m1host = m1src.filter((m) => (m.cells || []).length).pop();
  if (m1host) {
    const dropped = m1host.cells.pop();
    const a = assemble(m1src);
    out.m1 = {
      kind: 'drop-one-cell/coverage-must-report-a-gap',
      dropped: `${dropped.app}/${dropped.presentation}/${dropped.theme}/${dropped.state}`,
      baseNeverAttempted: base.coverage.neverAttempted,
      mutatedNeverAttempted: a.coverage.neverAttempted,
      pass: a.coverage.neverAttempted === base.coverage.neverAttempted + 1,
    };
  } else out.m1 = { kind: 'drop-one-cell', pass: null, note: 'n/a — no cells' };

  // M2 — flatten the sha256 of every cell so the chosen axis moves nothing. The axis
  // picked is whichever one the real run reported EFFECTIVE, so the control attacks a
  // check that was actually passing rather than one already failing.
  const live = base.axisEffectiveness.find((a) => a.verdict === 'effective');
  if (live) {
    const m2src = clone();
    for (const m of m2src) for (const c of m.cells || []) if (c.ok) c.sha256 = 'f'.repeat(64);
    const a = assemble(m2src);
    const after = a.axisEffectiveness.find((x) => x.axis === live.axis);
    out.m2 = {
      kind: 'flatten-images/axis-must-be-reported-decorative',
      axis: live.axis,
      baseVerdict: live.verdict,
      mutatedVerdict: after.verdict,
      pass: after.verdict === 'decorative',
    };
  } else out.m2 = { kind: 'flatten-images', pass: null, note: 'n/a — no axis was effective in the source run, so there is nothing to break' };

  // M3 — corrupt one indexed sha256. Only meaningful while the PNG is on disk.
  const onDisk = allCells.find((c) => c.ok && c.file && fs.existsSync(path.join(SHOTS_ROOT, c.file)));
  if (onDisk) {
    const m3src = clone();
    const target = m3src.flatMap((m) => m.cells || []).find((c) => c.file === onDisk.file);
    target.sha256 = `0${target.sha256.slice(1)}`;
    const a = assemble(m3src);
    out.m3 = {
      kind: 'corrupt-one-sha/integrity-must-report-mismatch',
      file: onDisk.file,
      baseMismatch: base.integrity.mismatch,
      mutatedMismatch: a.integrity.mismatch,
      pass: a.integrity.mismatch === base.integrity.mismatch + 1,
    };
  } else {
    out.m3 = {
      kind: 'corrupt-one-sha',
      pass: null,
      note: 'n/a — no indexed PNG is on disk (debug/ is gitignored and gets cleaned), so integrity cannot be falsified in this run',
    };
  }

  // M4 — remove an entire app's cells.
  const apps = [...new Set(allCells.map((c) => c.app))];
  if (apps.length > 1) {
    const victim = apps[0];
    const m4src = clone();
    for (const m of m4src) m.cells = (m.cells || []).filter((c) => c.app !== victim);
    const a = assemble(m4src);
    const lost = base.coverage.capturedCells - a.coverage.capturedCells;
    const expected = allCells.filter((c) => c.app === victim && c.ok).length;
    out.m4 = {
      kind: 'drop-one-app/coverage-must-fall-by-exactly-that-app',
      app: victim,
      expectedLoss: expected,
      observedLoss: lost,
      pass: lost === expected && expected > 0,
    };
  } else out.m4 = { kind: 'drop-one-app', pass: null, note: `n/a — only ${apps.length} app in the run` };

  /**
   * M5 — THE MERGE ITSELF. Added with multi-manifest support, because that code path is the
   * one thing here that can silently DROP evidence: if two runs claim the same cell, one
   * photograph shadows the other and every downstream number is computed over a set the
   * atlas never accounted for. The control copies a cell from the first run into the
   * second and asserts the merge reports exactly one collision AND refuses to certify.
   * Without this, the collision branch would be a plausible check that had never fired.
   */
  if (manifests.length > 1 && (manifests[0].cells || []).length) {
    const m5src = clone();
    const stowaway = JSON.parse(JSON.stringify(m5src[0].cells[0]));
    m5src[1].cells.push(stowaway);
    const a = assemble(m5src);
    out.m5 = {
      kind: 'duplicate-a-cell-across-runs/merge-must-report-a-collision',
      cell: `${stowaway.app}/${stowaway.presentation}/${stowaway.theme}/${stowaway.state}`,
      baseCollisions: base.coverage.mergeCollisions,
      mutatedCollisions: a.coverage.mergeCollisions,
      mutatedCertifiable: a.certifiable,
      pass: a.coverage.mergeCollisions === base.coverage.mergeCollisions + 1 && a.certifiable === false,
    };
  } else {
    out.m5 = {
      kind: 'duplicate-a-cell-across-runs',
      pass: null,
      note: `n/a — ${manifests.length} source manifest(s), so there is no merge to falsify`,
    };
  }

  /**
   * M6 — THE UNAVAILABILITY RULE ITSELF. `unavailability()` decides which non-captured
   * cells are a product gap rather than a failure, and a rule that only ever says
   * "product gap" would hide every real capture failure behind a shrug. The control makes
   * ONE cell of an all-unreached group succeed: the surface then demonstrably CAN reach
   * that value, so its remaining cells must be reclassified `failed` and must block.
   */
  const gapRow = base.coverage.unavailableByAxis[0];
  if (gapRow) {
    const m6src = clone();
    const field = gapRow.axis === 'state' ? 'stateReached' : 'presentationReached';
    // The group is per MANIFEST — unavailability is derived per run — so the control must
    // damage one run's group and expect the delta in that run alone.
    const host = m6src.find((m) => (m.cells || [])
      .filter((c) => c.app === gapRow.app && c[gapRow.axis] === gapRow.value && c[field] === false).length >= 2);
    const victims = host.cells.filter((c) => c.app === gapRow.app && c[gapRow.axis] === gapRow.value && c[field] === false);
    victims[0][field] = true;
    const a = assemble(m6src);
    /**
     * EVERY cell of the group becomes a failure, not all-but-one: the flipped cell still
     * has `ok: false`, so once the surface has demonstrably reached that axis value at
     * least once, its whole group is capture failures. Getting this expectation wrong by
     * one is how the control first ran — it read 13 against a predicted 12 and correctly
     * reported itself failing rather than being rounded to a pass.
     */
    out.m6 = {
      kind: 'one-cell-of-a-gap-group-reaches-the-axis/the-whole-group-must-become-failures',
      group: `${gapRow.app}/${gapRow.axis}=${gapRow.value} in ${host.__file} (${victims.length} cells)`,
      baseFailed: base.coverage.failedCells,
      expectedFailed: base.coverage.failedCells + victims.length,
      mutatedFailed: a.coverage.failedCells,
      mutatedCertifiable: a.certifiable,
      pass: a.coverage.failedCells === base.coverage.failedCells + victims.length && a.certifiable === false,
    };
  } else out.m6 = { kind: 'one-cell-of-a-gap-group-reaches-the-axis', pass: null, note: 'n/a — no surface/axis gap in these runs, so the rule has no subject' };

  const total = Object.keys(out).length;
  const fired = Object.values(out).filter((c) => c.pass === true).length;
  const failed = Object.values(out).filter((c) => c.pass === false).length;
  return { ...out, summary: { fired, failed, notApplicable: total - fired - failed } };
}

// ---------------------------------------------------------------------------------
(() => {
  const manifestPaths = arg('manifest', path.join('debug', 'l12-matrix-manifest.json'))
    .split(',').map((s) => s.trim()).filter(Boolean)
    .map((s) => path.resolve(REPO, s));
  if (!manifestPaths.length) {
    console.error('REFUSE - --manifest resolved to no files.');
    process.exit(2);
  }
  if (!fs.existsSync(SHOTS_ROOT)) {
    console.error(`REFUSE - --shots-root ${SHOTS_ROOT} does not exist.`);
    process.exit(2);
  }
  const manifests = [];
  for (const p of manifestPaths) {
    if (!fs.existsSync(p)) {
      console.error(`REFUSE - no matrix manifest at ${p}. Run l12-visual-matrix.cjs first.`);
      process.exit(2);
    }
    const m = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (m.schema !== 'l12-visual-matrix/v1') {
      console.error(`REFUSE - ${p} is schema '${m.schema}', not l12-visual-matrix/v1`);
      process.exit(2);
    }
    m.__file = path.relative(REPO, p).replace(/\\/g, '/');
    manifests.push(m);
  }

  const atlas = assemble(manifests);
  atlas.sourceManifest = manifests.map((m) => m.__file).join(',');
  if (has('control')) atlas.mutationControls = runControls(manifests, atlas);
  else atlas.mutationControls = null;

  const sheetPath = path.resolve(REPO, arg('sheet', path.join('debug', 'shots', 'l12-atlas.html')));
  fs.mkdirSync(path.dirname(sheetPath), { recursive: true });
  fs.writeFileSync(sheetPath, contactSheet(atlas, sheetPath));
  atlas.contactSheet = path.relative(REPO, sheetPath).replace(/\\/g, '/');

  const outPath = path.resolve(REPO, arg('out', path.join('src', '.coordination', 'liquid-workplace', 'baselines', 'l12-atlas.json')));
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, `${JSON.stringify(atlas, null, 2)}\n`);

  console.log(JSON.stringify({
    out: path.relative(REPO, outPath).replace(/\\/g, '/'),
    sheet: atlas.contactSheet,
    sources: atlas.sources.map((s) => `${s.manifest} (${s.coverage.capturedCells}/${s.coverage.declaredCells}, certifiable ${s.certifiable})`),
    shotsRoot: atlas.shotsRoot,
    plates: atlas.plates.length,
    coverage: atlas.coverage,
    axes: Object.fromEntries(atlas.axisEffectiveness.map((a) => [a.axis, a.verdict])),
    integrity: atlas.integrity.state,
    distinctImages: atlas.duplication.distinctImages,
    certifiable: atlas.certifiable,
    blockers: atlas.blockers,
    productGaps: atlas.productGaps,
    controls: atlas.mutationControls && atlas.mutationControls.summary,
  }, null, 2));
  process.exit(atlas.certifiable ? 0 : 1);
})();
