/**
 * The transport that lets an Agent-generated card batch reach AI Card Studio's
 * own editor, so the user previews and corrects it before anything is written.
 *
 * `flashcard.generate-cards` deliberately writes nothing (see
 * `renderer/cardStudioAgentHandlers.ts`): it runs the studio's pipeline and
 * returns rows. That was the right half to build first, but on its own it leaves
 * the conversion the plan asked for incomplete — the plan's wording is "convert
 * specialized generation experiences such as AI Card Studio into Agent
 * skills/workflows **while preserving rich dedicated editors for preview and
 * correction**", and a batch that only ever exists as rows in a chat reaches no
 * editor at all. The user's only route to a deck was `flashcard.add-cards`,
 * which writes what it was handed, sight unseen.
 *
 * So a generated batch is staged, and the studio adopts it into the same
 * `batchResults` state a locally generated batch lands in. Every action the
 * studio already offers — the preview strip, Save to flashcards, Send to Anki,
 * Export CSV — then works on it identically, because it *is* the same state.
 *
 * ## Why this is a fourth route rather than one of the three that exist
 *
 * The same three routes `agentImageStaging.ts` rules out are wrong here for the
 * same reasons, and one more: the studio is not conversation-scoped. It has no
 * conversation id, so the persisted workspace and the session context — both
 * keyed by conversation — cannot address it, and a renderer-held copy does not
 * cross from the Agent pop-out to the Flashcards window. Main-process memory is
 * what is left. Nothing here touches `fs`.
 *
 * ## One slot, not a map
 *
 * `agentImageStaging` keys by conversation because the Agent shell claims by
 * selecting one. Nothing analogous exists here: the claimant is a form in the
 * Flashcards window that knows only that it is open. So this store holds **one**
 * batch — the most recent — and a second stage replaces an unclaimed first
 * rather than queueing behind it. That is reported back to the stager
 * (`replacedUnclaimed`) rather than being silent, because "generate again" is a
 * gesture the user makes and the earlier batch really is gone.
 *
 * ## Claiming never destroys visible work
 *
 * A claim is single-use, exactly like the image lane. The consequence is one the
 * image lane does not have: the studio may already be showing an unsaved batch
 * the user generated by hand, and adopting over it would delete work that is on
 * screen and has never been written anywhere. So the studio claims only into an
 * empty preview — `shouldClaimAgentCardBatch` is that rule, in shared code so
 * the test can hold it rather than the component's own conditional. A batch that
 * cannot be adopted stays in main and is picked up the next time the studio is
 * mounted with an empty preview, or expires.
 */

import type { AiEnrichmentResult, AiGeneratedCard } from './miningTypes';

export const AGENT_CARD_BATCH_STAGING_CHANNELS = {
  stage: 'agentCardBatchStaging:stage',
  take: 'agentCardBatchStaging:take',
  /**
   * Main → every window, after a batch is accepted.
   *
   * The studio claims on mount, which covers "the user walks to Flashcards
   * afterwards". This covers the other order: Flashcards already open in a
   * second window while the Agent generates in the first. The payload is the
   * batch id and nothing else — the cards stay in main until a window claims
   * them, so the announcement can never be the thing that copies a batch into a
   * renderer that was not asking for one.
   */
  staged: 'agentCardBatchStaging:staged',
} as const;

/**
 * How long an unclaimed batch survives in main.
 *
 * Three times the image lane's ten minutes, and the difference is deliberate. A
 * staged screenshot is incidental material the user did not ask the app to keep,
 * so its TTL is a promise to forget. A card batch is study material the user
 * explicitly asked to be generated — and paid a provider call for — so the risk
 * being managed is the opposite one: dropping it before the user has walked from
 * the Agent window to Flashcards. Half an hour covers that walk and still keeps
 * "the app forgets things you did not save" true.
 */
export const AGENT_CARD_BATCH_STAGING_TTL_MS = 30 * 60_000;
/** The adapter's own `MAX_TERMS`. A batch cannot contain more words than it enriched. */
export const AGENT_CARD_BATCH_RESULT_LIMIT = 25;
/** The adapter's own `MAX_CARD_COUNT` ceiling, per word. */
export const AGENT_CARD_BATCH_CARDS_PER_RESULT_LIMIT = 10;
/**
 * A whole-payload ceiling, applied after normalization to the JSON that is
 * actually retained. The per-field bounds below already make a batch far smaller
 * than this; the ceiling exists so a caller cannot assemble a large one out of
 * many individually legal fields.
 */
export const AGENT_CARD_BATCH_BYTES_LIMIT = 2 * 1024 * 1024;

const TEXT_MAX = 4_000;
/** `csv` is a whole batch block for one word, so it gets its own larger bound. */
const CSV_MAX = 20_000;
const LABEL_MAX = 200;
const TAG_LIMIT = 24;
const FREQUENCY_KEY_LIMIT = 24;
const SOURCE_MAX = 40;
const DECK_LABEL_MAX = 200;
const BATCH_ID_MAX = 180;

export type AgentCardBatchStagingFailureCode =
  | 'invalid-request'
  | 'too-large'
  | 'bridge-unavailable';

/** What the studio is told about where a claimed batch came from. */
export interface AgentStagedCardBatch {
  id: string;
  /**
   * The deck title the studio should offer for this batch, already resolved by
   * the stager. For a `book` run that is `miningDeckIdentity`'s deck title, so
   * an agent batch saves into the same group a manual mining run of the same
   * range would; otherwise it is the preset's own `<label> studio`, which is
   * exactly what the studio's Save button builds for a local batch.
   */
  deckLabel: string;
  /**
   * The group key `deckLabel` belongs to, when the stager knows one that the
   * label alone cannot reproduce.
   *
   * `saveAiResultsToDeck` derives its id with `deckBookId`, which slugs on
   * `[^\w]+`; `\w` is ASCII-only, so **every** Japanese title collapses to the
   * same slug (`chapterRange.ts` records the collision, and
   * `chapterRange.test.ts` asserts it). For the studio's own batches the title
   * is an English preset label, so that never bites. A `book` batch's label is
   * the book's real title, so two different Japanese novels would derive the
   * same id — and `replaceImportedDeck` DELETES the matched group before
   * inserting, so saving one would destroy the other.
   *
   * `miningDeckIdentity` already solves this by deriving from the item id, so
   * the id is carried rather than re-derived. Absent for `preset` and
   * `dictionary` batches, which have no item and whose labels are ASCII.
   */
  deckBookId?: string;
  /** `preset` | `dictionary` | `book`, as the adapter reported it. Display only. */
  source: string;
  results: AiEnrichmentResult[];
}

export interface AgentCardBatchStageRequest {
  deckLabel: string;
  deckBookId?: string;
  source: string;
  results: AiEnrichmentResult[];
}

export type AgentCardBatchStageResult =
  | { ok: true; results: number; cards: number; replacedUnclaimed: boolean }
  | { ok: false; code: AgentCardBatchStagingFailureCode };

export type AgentCardBatchTakeResult =
  | { ok: true; batch: AgentStagedCardBatch | null }
  | { ok: false; code: AgentCardBatchStagingFailureCode };

function boundedText(value: unknown, max: number): string {
  return typeof value === 'string' ? value.slice(0, max) : '';
}

function boundedTags(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  const tags: string[] = [];
  for (const entry of value) {
    const tag = boundedText(entry, LABEL_MAX).trim();
    if (tag) tags.push(tag);
    if (tags.length >= TAG_LIMIT) break;
  }
  return tags;
}

/**
 * `frequencies` is a `Record<string, number>` whose keys are corpus names, so it
 * is the one open-ended shape in the payload. Bounded by key count and by key
 * length, and non-finite values are dropped rather than coerced — a `NaN` that
 * survives here reaches Anki's frequency field as text.
 */
function boundedFrequencies(value: unknown): Record<string, number> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  const out: Record<string, number> = {};
  let count = 0;
  for (const [key, raw] of Object.entries(value as Record<string, unknown>)) {
    if (count >= FREQUENCY_KEY_LIMIT) break;
    const name = key.slice(0, LABEL_MAX).trim();
    if (!name) continue;
    if (typeof raw !== 'number' || !Number.isFinite(raw)) continue;
    out[name] = raw;
    count += 1;
  }
  return out;
}

function normalizeCard(value: unknown): AiGeneratedCard | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = value as Record<string, unknown>;
  const front = boundedText(raw.front, TEXT_MAX);
  const back = boundedText(raw.back, TEXT_MAX);
  // A card with neither face is nothing to preview and nothing to save; the
  // studio would render an empty strip entry for it.
  if (!front.trim() && !back.trim()) return null;
  return {
    formatId: boundedText(raw.formatId, LABEL_MAX),
    label: boundedText(raw.label, LABEL_MAX),
    front,
    back,
    tags: boundedTags(raw.tags),
  };
}

/**
 * One enriched word, bounded field by field.
 *
 * Every field the studio's four actions read is carried, so an adopted batch
 * behaves identically to a locally generated one: `expression`/`reading`/
 * `meaning`/`sentence` and the six translation fields for Anki, `imageHtml` for
 * the picture, `cards` for the preview and the deck save, `csv` for the export.
 *
 * **`rawJson` is deliberately dropped**, and it is the only field that is. It is
 * the model's unparsed reply, its size is the model's to decide rather than this
 * contract's, and nothing in the renderer reads it — so carrying it would be
 * paying an unbounded transport cost for a field no claimant can use. It is
 * emitted as `''` rather than omitted, so the claimed value is still an
 * `AiEnrichmentResult` and no consumer has to special-case an agent batch.
 */
function normalizeResult(value: unknown): AiEnrichmentResult | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = value as Record<string, unknown>;
  const expression = boundedText(raw.expression, LABEL_MAX).trim();
  if (!expression) return null;

  const cards: AiGeneratedCard[] = [];
  if (Array.isArray(raw.cards)) {
    for (const entry of raw.cards) {
      const card = normalizeCard(entry);
      if (card) cards.push(card);
      if (cards.length >= AGENT_CARD_BATCH_CARDS_PER_RESULT_LIMIT) break;
    }
  }
  // A word with no card is not a preview row and not a saved card. Refusing it
  // here is what stops a claimed batch from reporting a count the studio's own
  // `minedCardCount` will not agree with.
  if (!cards.length) return null;

  return {
    presetId: boundedText(raw.presetId, LABEL_MAX),
    formatId: boundedText(raw.formatId, LABEL_MAX),
    expression,
    reading: boundedText(raw.reading, LABEL_MAX),
    meaning: boundedText(raw.meaning, TEXT_MAX),
    nuance: boundedText(raw.nuance, TEXT_MAX),
    sentence: boundedText(raw.sentence, TEXT_MAX),
    sentenceTranslationEn: boundedText(raw.sentenceTranslationEn, TEXT_MAX),
    sentenceTranslationRu: boundedText(raw.sentenceTranslationRu, TEXT_MAX),
    sentenceTranslationZh: boundedText(raw.sentenceTranslationZh, TEXT_MAX),
    meaningRu: boundedText(raw.meaningRu, TEXT_MAX),
    meaningZh: boundedText(raw.meaningZh, TEXT_MAX),
    grammarBreakdown: boundedText(raw.grammarBreakdown, TEXT_MAX),
    culturalContext: boundedText(raw.culturalContext, TEXT_MAX),
    properNameNotes: boundedText(raw.properNameNotes, TEXT_MAX),
    toponymNotes: boundedText(raw.toponymNotes, TEXT_MAX),
    tags: boundedTags(raw.tags),
    imageQuery: boundedText(raw.imageQuery, LABEL_MAX),
    imageHtml: boundedText(raw.imageHtml, TEXT_MAX),
    suggestedFront: boundedText(raw.suggestedFront, TEXT_MAX),
    suggestedBack: boundedText(raw.suggestedBack, TEXT_MAX),
    cards,
    csv: boundedText(raw.csv, CSV_MAX),
    frequencies: boundedFrequencies(raw.frequencies),
    rawJson: '',
  };
}

function normalizeResults(value: unknown): AiEnrichmentResult[] {
  if (!Array.isArray(value)) return [];
  const results: AiEnrichmentResult[] = [];
  for (const entry of value) {
    const result = normalizeResult(entry);
    if (result) results.push(result);
    if (results.length >= AGENT_CARD_BATCH_RESULT_LIMIT) break;
  }
  return results;
}

export function normalizeAgentCardBatchStageRequest(
  value: unknown,
): AgentCardBatchStageRequest | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = value as Record<string, unknown>;
  const deckLabel = boundedText(raw.deckLabel, DECK_LABEL_MAX).trim();
  if (!deckLabel) return null;
  const results = normalizeResults(raw.results);
  // An empty batch is not a thing to review. Accepting one would light the
  // studio's banner for a preview with nothing in it.
  if (!results.length) return null;
  const deckBookId = boundedText(raw.deckBookId, DECK_LABEL_MAX).trim();
  return {
    deckLabel,
    ...(deckBookId ? { deckBookId } : {}),
    source: boundedText(raw.source, SOURCE_MAX).trim(),
    results,
  };
}

/** How many cards a normalized batch carries. The count the studio will show. */
export function agentCardBatchCardCount(results: readonly AiEnrichmentResult[]): number {
  return results.reduce((sum, result) => sum + result.cards.length, 0);
}

/**
 * The whole-payload ceiling, measured on the normalized batch.
 *
 * Measured rather than estimated, and measured on what would be *retained*
 * rather than on what arrived, so the number the bound is compared against is
 * the number of bytes main would actually hold.
 */
export function agentCardBatchBytes(request: AgentCardBatchStageRequest): number {
  return JSON.stringify(request.results).length;
}

/**
 * Whether the studio may adopt a staged batch right now.
 *
 * The whole rule is "only into an empty preview", and it lives here rather than
 * inside the component so a test can hold it. A claim is single-use: taking a
 * batch while the studio is showing an unsaved local one would replace work that
 * is on screen and has never been written to a deck, and there would be nothing
 * to restore it from.
 */
export function shouldClaimAgentCardBatch(currentResultCount: number): boolean {
  return currentResultCount === 0;
}

function normalizeStagedBatch(value: unknown): AgentStagedCardBatch | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = value as Record<string, unknown>;
  const id = boundedText(raw.id, BATCH_ID_MAX).trim();
  const deckLabel = boundedText(raw.deckLabel, DECK_LABEL_MAX).trim();
  if (!id || !deckLabel) return null;
  const results = normalizeResults(raw.results);
  if (!results.length) return null;
  const deckBookId = boundedText(raw.deckBookId, DECK_LABEL_MAX).trim();
  return {
    id,
    deckLabel,
    ...(deckBookId ? { deckBookId } : {}),
    source: boundedText(raw.source, SOURCE_MAX).trim(),
    results,
  };
}

/**
 * Renderer-side validation of what main handed back.
 *
 * Symmetrical with `agentImageStaging.ts` and for the same reason: an IPC reply
 * is not trusted because it arrived over IPC. Re-normalizing here also means the
 * studio can only ever adopt a batch that satisfies the same bounds main
 * accepted, so a preview count and a saved-card count cannot disagree.
 */
export function normalizeAgentCardBatchTakeResult(value: unknown): AgentCardBatchTakeResult {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, code: 'bridge-unavailable' };
  }
  const raw = value as Record<string, unknown>;
  if (raw.ok === true) {
    // `null` is the ordinary answer, not a failure: almost every mount claims
    // into an empty store.
    return { ok: true, batch: raw.batch == null ? null : normalizeStagedBatch(raw.batch) };
  }
  const code = raw.code;
  return {
    ok: false,
    code: code === 'invalid-request' || code === 'too-large' ? code : 'bridge-unavailable',
  };
}

export function normalizeAgentCardBatchStageResult(value: unknown): AgentCardBatchStageResult {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, code: 'bridge-unavailable' };
  }
  const raw = value as Record<string, unknown>;
  if (
    raw.ok === true
    && typeof raw.results === 'number' && Number.isSafeInteger(raw.results)
    && typeof raw.cards === 'number' && Number.isSafeInteger(raw.cards)
  ) {
    return {
      ok: true,
      results: raw.results,
      cards: raw.cards,
      replacedUnclaimed: raw.replacedUnclaimed === true,
    };
  }
  const code = raw.code;
  return {
    ok: false,
    code: code === 'invalid-request' || code === 'too-large' ? code : 'bridge-unavailable',
  };
}
