import type { AiMiningCardFormat, AiPromptPreset } from './mining';

type PresetDef = AiPromptPreset & { format: AiMiningCardFormat };

function preset(
  id: string,
  label: string,
  category: AiPromptPreset['category'],
  description: string,
  instruction: string,
  format: Omit<AiMiningCardFormat, 'presetId' | 'id'> & { id: string },
): PresetDef {
  return {
    id,
    label,
    category,
    description,
    instruction,
    format: { ...format, presetId: id },
  };
}

const CATALOG: PresetDef[] = [
  preset(
    'idiom-slang',
    'Idiom / Slang Breakdown',
    'core',
    'Figurative meaning, register, and who would naturally say it.',
    'Explain the figurative or slang meaning. Include literal gloss, pragmatic nuance, typical speaker, and what sounds wrong if translated literally.',
    {
      id: 'idiom-slang-recognition',
      label: 'Idiom recognition (JP → gloss)',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Japanese idiom in context on the front; figurative meaning, nuance, and Russian gloss on the back.',
      cardTemplates: [
        {
          label: 'Idiom recognition',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nFigurative: {meaning}\n\nNuance: {nuance}\n\nRU: {sentenceTranslationRu}\n\nRegister: {culturalContext}',
          tags: ['ai-idiom', 'recognition'],
        },
      ],
    },
  ),
  preset(
    'idiom-reverse',
    'Idiom Reverse Production',
    'core',
    'Multilingual cues that force recall of the Japanese idiom.',
    'Frame production prompts from English and Russian paraphrases of the idiom meaning. Keep cues natural, not word-for-word translations of the Japanese surface form.',
    {
      id: 'idiom-reverse-trilingual',
      label: 'Reverse idiom set (EN / RU / ZH cue)',
      profileId: 'seed-trilingual',
      outputFormat: 'csv',
      description: 'Three production cards: English meaning → JA, Russian meaning → JA, and a Chinese/English blended cue → JA.',
      cardTemplates: [
        {
          label: 'EN meaning → Japanese idiom',
          front: 'English paraphrase:\n{meaning}\n\nWhich Japanese idiom fits?',
          back: '{expression}\n{reading}\n\n{sentence}\n\nNuance: {nuance}',
          tags: ['ai-idiom', 'reverse', 'en'],
        },
        {
          label: 'RU meaning → Japanese idiom',
          front: 'Russian paraphrase:\n{sentenceTranslationRu}\n\nКакое японское выражение?',
          back: '{expression}\n{reading}\n\nFigurative: {meaning}\n\n{sentence}',
          tags: ['ai-idiom', 'reverse', 'ru'],
        },
        {
          label: 'ZH/EN blended cue → Japanese idiom',
          front: 'Cue:\n{toponymNotes}\n{meaning}\n\nRecall the Japanese expression.',
          back: '{expression}\n{reading}\n\n{sentence}\n\nCulture: {culturalContext}',
          tags: ['ai-idiom', 'reverse', 'zh-en'],
        },
      ],
    },
  ),
  preset(
    'idiom-cloze',
    'Idiom Context Cloze',
    'core',
    'Hide the idiom inside its EPUB sentence and test recall from context.',
    'Treat the token as a cloze target inside the sentence. Explain why surrounding context constrains the missing expression.',
    {
      id: 'idiom-cloze-context',
      label: 'Context cloze idiom',
      profileId: 'seed-context-cloze',
      outputFormat: 'anki',
      description: 'Sentence with the idiom blanked; back reveals reading, meaning, and nuance.',
      cardTemplates: [
        {
          label: 'Idiom cloze',
          front: '{cloze-before}[ … ]{cloze-after}\n\nWhat expression is missing?',
          back: '{expression}（{reading}）\n\n{meaning}\n\nNuance: {nuance}',
          tags: ['ai-idiom', 'cloze'],
        },
      ],
    },
  ),
  preset(
    'proper-name',
    'Proper Name Identification',
    'core',
    'Character names, titles, historical figures, and fictional naming patterns.',
    'Determine whether the token is a personal name, title, historical figure, or fictional naming pattern. Explain reading clues and why a dictionary gloss may fail.',
    {
      id: 'proper-name-id',
      label: 'Name identification card',
      profileId: 'seed-reading-first',
      outputFormat: 'anki',
      description: 'Surface form in context; back explains entity type, reading, and narrative role.',
      cardTemplates: [
        {
          label: 'Proper name ID',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nEntity: {properNameNotes}\n\nRole/meaning: {meaning}\n\nFrequency: {frequency}',
          tags: ['ai-name'],
        },
      ],
    },
  ),
  preset(
    'city-toponym',
    'City / Toponym Analysis',
    'core',
    'Real cities, historical places, and fantasy landmarks.',
    'Determine geographic or fictional place status. Explain location hierarchy, historical rename patterns, and how the place functions in the plot.',
    {
      id: 'toponym-location',
      label: 'Toponym recognition',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Place name in context; back gives location notes and cultural framing.',
      cardTemplates: [
        {
          label: 'Toponym card',
          front: '{expression}\n\nWhere is this in the story/world?',
          back: '{reading}\n\n{toponymNotes}\n\nContext: {culturalContext}\n\nGloss: {meaning}',
          tags: ['ai-toponym'],
        },
      ],
    },
  ),
  preset(
    'grammar-deconstruction',
    'Grammar Deconstruction',
    'core',
    'Particles, auxiliaries, conjugation stacks, and compressed grammar.',
    'Deconstruct the phrase step by step. Separate particles, auxiliaries, inflections, and compounds. Give base dictionary forms and why the stack is hard.',
    {
      id: 'grammar-step-stack',
      label: 'Grammar stack breakdown',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Difficult phrase in its sentence; back is a layered grammar explanation.',
      cardTemplates: [
        {
          label: 'Grammar breakdown',
          front: '{expression}\n\n{sentence}',
          back: 'Breakdown:\n{grammarBreakdown}\n\nOverall: {meaning}\n\nNuance: {nuance}',
          tags: ['ai-grammar'],
        },
      ],
    },
  ),
  preset(
    'archaic-terms',
    'Archaic / Literary Register',
    'specialized',
    'Old-fashioned, literary, or pre-modern wording in modern fiction.',
    'Explain archaic or elevated diction. Contrast with the modern equivalent, note era/register, and show how the word differs from its everyday form.',
    {
      id: 'archaic-register-contrast',
      label: 'Archaic ↔ modern contrast',
      profileId: 'seed-ja-immersion',
      outputFormat: 'anki',
      description: 'Literary surface form on the front; back contrasts modern paraphrase and register notes.',
      cardTemplates: [
        {
          label: 'Archaic contrast',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nModern paraphrase: {meaning}\n\nRegister: {culturalContext}\n\nNotes: {nuance}',
          tags: ['ai-archaic'],
        },
      ],
    },
  ),
  preset(
    'kansai-dialect',
    'Kansai / Dialect Analysis',
    'specialized',
    'Regional forms, dialect particles, and standard Japanese equivalents.',
    'Identify dialect features (Kansai or other). Give standard Japanese equivalent, social nuance, and whether the form marks character voice.',
    {
      id: 'dialect-standard-pair',
      label: 'Dialect → standard pair',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Dialect form in dialogue; back shows standard form and character-voice notes.',
      cardTemplates: [
        {
          label: 'Dialect pair',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nStandard: {meaning}\n\nDialect note: {culturalContext}\n\nNuance: {nuance}',
          tags: ['ai-dialect'],
        },
      ],
    },
  ),
  preset(
    'onomatopoeia',
    'Onomatopoeia / Mimetic Words',
    'specialized',
    'Giongo, gitaigo, and texture/motion mimetics.',
    'Classify the mimetic (sound, motion, texture, state). Explain English/Russian renderings, what imagery it evokes, and collocations.',
    {
      id: 'mimetic-sensory',
      label: 'Sensory mimetic card',
      profileId: 'seed-image-mine',
      outputFormat: 'anki',
      description: 'Mimetic in context; back focuses on sensory imagery and translation options.',
      cardTemplates: [
        {
          label: 'Mimetic sensory',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nSense/type: {nuance}\n\nRenderings: {meaning}\n\nImagery: {culturalContext}',
          tags: ['ai-mimetic'],
        },
      ],
    },
  ),
  preset(
    'keigo-polite',
    'Keigo / Polite Speech',
    'specialized',
    'Honorific, humble, and polite alternations tied to social context.',
    'Explain keigo level (尊敬・謙譲・丁寧). Give plain/casual counterpart, who speaks to whom, and why this form appears in the sentence.',
    {
      id: 'keigo-level-map',
      label: 'Keigo level map',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Polite surface form; back maps keigo type, plain form, and social context.',
      cardTemplates: [
        {
          label: 'Keigo map',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nKeigo analysis:\n{grammarBreakdown}\n\nPlain equivalent: {meaning}\n\nSituation: {culturalContext}',
          tags: ['ai-keigo'],
        },
      ],
    },
  ),
  preset(
    'pop-culture',
    'Pop-Culture Allusion',
    'specialized',
    'References to anime, games, idols, memes, or shared cultural touchstones.',
    'Identify the pop-culture reference or trope. Explain what a native fan would infer and what knowledge is assumed.',
    {
      id: 'popculture-allusion',
      label: 'Allusion explainer',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Token in context; back unpacks the referenced work, trope, or fandom meaning.',
      cardTemplates: [
        {
          label: 'Pop-culture allusion',
          front: '{expression}\n\n{sentence}',
          back: 'Reference: {culturalContext}\n\nMeaning here: {meaning}\n\nNuance: {nuance}',
          tags: ['ai-popculture'],
        },
      ],
    },
  ),
  preset(
    'nuance-comparator',
    'Near-Synonym Comparator',
    'specialized',
    'Contrast easily confused words with usage boundaries.',
    'Compare the target to 1–2 near synonyms. Explain nuance, collocations, formality, and which slot in the sentence each would fit.',
    {
      id: 'synonym-contrast-table',
      label: 'Synonym contrast card',
      profileId: 'seed-en-pairs',
      outputFormat: 'anki',
      description: 'Target word in context; back contrasts confusable alternatives side by side.',
      cardTemplates: [
        {
          label: 'Synonym contrast',
          front: '{expression}\n\n{sentence}',
          back: 'Core meaning: {meaning}\n\nContrast:\n{nuance}\n\nWhen to use this one: {culturalContext}',
          tags: ['ai-synonym'],
        },
      ],
    },
  ),
  preset(
    'historical-register',
    'Historical / Period Register',
    'specialized',
    'Wartime, Edo-period, or era-specific vocabulary in fiction.',
    'Place the term in its historical period. Explain modern reader knowledge assumed and neutral modern paraphrase.',
    {
      id: 'historical-era-note',
      label: 'Era register note',
      profileId: 'seed-ja-immersion',
      outputFormat: 'anki',
      description: 'Period term in context; back anchors era, modern gloss, and narrative function.',
      cardTemplates: [
        {
          label: 'Historical register',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nEra/context: {culturalContext}\n\nModern gloss: {meaning}\n\nNotes: {properNameNotes}',
          tags: ['ai-historical'],
        },
      ],
    },
  ),
  preset(
    'literary-metaphor',
    'Literary Metaphor',
    'specialized',
    'Figurative descriptions, personification, and compressed imagery.',
    'Unpack metaphorical language. Separate literal scene description from figurative reading and authorial tone.',
    {
      id: 'metaphor-layers',
      label: 'Metaphor layer card',
      profileId: 'seed-reading-first',
      outputFormat: 'anki',
      description: 'Figurative phrase in context; back separates literal vs figurative readings.',
      cardTemplates: [
        {
          label: 'Metaphor layers',
          front: '{expression}\n\n{sentence}',
          back: 'Literal scene: {meaning}\n\nFigurative read: {nuance}\n\nTone: {culturalContext}',
          tags: ['ai-metaphor'],
        },
      ],
    },
  ),
  preset(
    'internet-slang',
    'Internet / Meme Slang',
    'specialized',
    'Net slang, abbreviations, and chronically online phrasing.',
    'Explain internet/meme slang including reading, origin platform, tone (ironic/sincere), and safe vs cringe usage.',
    {
      id: 'net-slang-gloss',
      label: 'Net slang gloss',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Slang form in context; back gives origin, tone, and plain-language gloss.',
      cardTemplates: [
        {
          label: 'Internet slang',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nGloss: {meaning}\n\nOrigin/tone: {culturalContext}\n\nNuance: {nuance}',
          tags: ['ai-net-slang'],
        },
      ],
    },
  ),
  preset(
    'honorific-title',
    'Honorific Title Analysis',
    'specialized',
    'San, sama, sensei, job titles, and address patterns.',
    'Explain the honorific or title: social relationship, formality, gender/role cues, and what dropping or changing it would imply.',
    {
      id: 'honorific-relationship',
      label: 'Honorific relationship card',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Title/honorific in dialogue; back explains relationship and address rules.',
      cardTemplates: [
        {
          label: 'Honorific title',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nRelationship: {properNameNotes}\n\nUsage: {meaning}\n\nImplications: {nuance}',
          tags: ['ai-honorific'],
        },
      ],
    },
  ),
  preset(
    'buddhist-religious',
    'Buddhist / Religious Terms',
    'specialized',
    'Temple vocabulary, Buddhist concepts, and ritual language.',
    'Explain religious/Buddhist terminology with doctrinal gloss, everyday vs sect-specific usage, and story relevance.',
    {
      id: 'religious-doctrine',
      label: 'Religious term card',
      profileId: 'seed-ja-immersion',
      outputFormat: 'anki',
      description: 'Religious term in context; back gives doctrine gloss and narrative relevance.',
      cardTemplates: [
        {
          label: 'Religious term',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nDoctrine/idea: {meaning}\n\nContext: {culturalContext}\n\nNotes: {nuance}',
          tags: ['ai-religious'],
        },
      ],
    },
  ),
  preset(
    'military-terminology',
    'Military Terminology',
    'specialized',
    'Ranks, equipment, tactics, and war-fiction jargon.',
    'Explain military term: literal meaning, rank/equipment class, and whether usage is realistic or fictionalized.',
    {
      id: 'military-jargon',
      label: 'Military jargon card',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Military token in context; back defines jargon and realism notes.',
      cardTemplates: [
        {
          label: 'Military term',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nDefinition: {meaning}\n\nCategory: {properNameNotes}\n\nUsage: {nuance}',
          tags: ['ai-military'],
        },
      ],
    },
  ),
  preset(
    'legal-language',
    'Legal / Bureaucratic Language',
    'specialized',
    'Contracts, law, administration, and stiff formal wording.',
    'Explain legal/bureaucratic phrasing in plain Japanese and English. Note document type and typical collocations.',
    {
      id: 'legal-plain-paraphrase',
      label: 'Legal plain paraphrase',
      profileId: 'seed-minimal',
      outputFormat: 'anki',
      description: 'Formal legalistic phrase; back gives plain paraphrase and document context.',
      cardTemplates: [
        {
          label: 'Legal language',
          front: '{expression}\n\n{sentence}',
          back: 'Plain JP/EN: {meaning}\n\nStructure:\n{grammarBreakdown}\n\nRegister: {culturalContext}',
          tags: ['ai-legal'],
        },
      ],
    },
  ),
  preset(
    'medical-vocabulary',
    'Medical Vocabulary',
    'specialized',
    'Anatomy, symptoms, diagnoses, and clinical wording in fiction.',
    'Explain medical term with layperson gloss, reading certainty, and whether usage is clinical or colloquial in the scene.',
    {
      id: 'medical-lay-gloss',
      label: 'Medical lay gloss',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Medical term in context; back gives lay explanation and clinical notes.',
      cardTemplates: [
        {
          label: 'Medical vocab',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nLay gloss: {meaning}\n\nClinical note: {nuance}\n\nContext: {culturalContext}',
          tags: ['ai-medical'],
        },
      ],
    },
  ),
  preset(
    'fantasy-lore',
    'Fantasy Lore Term',
    'specialized',
    'Magic systems, races, artifacts, and in-world invented terms.',
    'Treat as in-universe lore. Explain worldbuilding function, etymology hints, and how the reader should infer meaning from context.',
    {
      id: 'fantasy-lore-entry',
      label: 'Fantasy lore entry',
      profileId: 'seed-image-mine',
      outputFormat: 'anki',
      description: 'In-world term; back documents lore role, inferred meaning, and story clues.',
      cardTemplates: [
        {
          label: 'Fantasy lore',
          front: '{expression}\n\n{sentence}',
          back: 'In-world role: {culturalContext}\n\nInferred meaning: {meaning}\n\nClues: {nuance}',
          tags: ['ai-fantasy'],
        },
      ],
    },
  ),
  preset(
    'sci-fi-terminology',
    'Sci-Fi Terminology',
    'specialized',
    'Technology, ships, cyberpunk, and speculative vocabulary.',
    'Explain sci-fi coinage or tech term: literal parts, English rendering, and whether it maps to a real concept.',
    {
      id: 'scifi-tech-gloss',
      label: 'Sci-fi tech gloss',
      profileId: 'seed-en-n3',
      outputFormat: 'anki',
      description: 'Tech/sci-fi term; back breaks down morphemes and English rendering.',
      cardTemplates: [
        {
          label: 'Sci-fi term',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nTech gloss: {meaning}\n\nComponents: {grammarBreakdown}\n\nUniverse note: {culturalContext}',
          tags: ['ai-scifi'],
        },
      ],
    },
  ),
  preset(
    'food-culture',
    'Food / Culinary Culture',
    'specialized',
    'Dishes, ingredients, preparation, and food-related customs.',
    'Explain food term with what it is, how it is eaten, regional/cultural association, and menu-reading tips.',
    {
      id: 'food-cultural-card',
      label: 'Food culture card',
      profileId: 'seed-image-mine',
      outputFormat: 'anki',
      description: 'Food term in context; back describes dish, culture, and reading help.',
      cardTemplates: [
        {
          label: 'Food culture',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nWhat it is: {meaning}\n\nCulture/custom: {culturalContext}\n\nTip: {nuance}',
          tags: ['ai-food'],
        },
      ],
    },
  ),
  preset(
    'seasonal-reference',
    'Seasonal / Cultural Calendar',
    'specialized',
    'Festivals, seasons, holidays, and calendar metaphors.',
    'Explain seasonal or festival reference: when it occurs, symbolic weight in literature, and emotional tone in the sentence.',
    {
      id: 'seasonal-symbolism',
      label: 'Seasonal symbolism card',
      profileId: 'seed-ja-immersion',
      outputFormat: 'anki',
      description: 'Seasonal reference in context; back explains calendar timing and literary symbolism.',
      cardTemplates: [
        {
          label: 'Seasonal reference',
          front: '{expression}\n\n{sentence}',
          back: 'Calendar/season: {culturalContext}\n\nMeaning here: {meaning}\n\nTone: {nuance}',
          tags: ['ai-seasonal'],
        },
      ],
    },
  ),
  preset(
    'school-speech',
    'School / Youth Speech',
    'specialized',
    'Classroom slang, club speech, and student register.',
    'Explain school-age phrasing: social group, formality vs family speech, and typical situations.',
    {
      id: 'school-youth-register',
      label: 'School youth register',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Student speech in context; back notes age register and social setting.',
      cardTemplates: [
        {
          label: 'School speech',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nGloss: {meaning}\n\nRegister: {culturalContext}\n\nWho says it: {nuance}',
          tags: ['ai-school'],
        },
      ],
    },
  ),
  preset(
    'business-japanese',
    'Business Japanese',
    'specialized',
    'Office email phrasing, meetings, and keigo-heavy workplace speech.',
    'Explain business Japanese chunk: function (request, apology, confirmation), safer alternatives, and email vs spoken use.',
    {
      id: 'business-phrase-function',
      label: 'Business phrase function',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Workplace phrase; back states communicative function and safer variants.',
      cardTemplates: [
        {
          label: 'Business Japanese',
          front: '{expression}\n\n{sentence}',
          back: 'Function: {meaning}\n\nBreakdown:\n{grammarBreakdown}\n\nAlternatives: {nuance}',
          tags: ['ai-business'],
        },
      ],
    },
  ),
  preset(
    'casual-masculine',
    'Casual Masculine Speech',
    'specialized',
    'Rough, bro-ish, or male-leaning casual phrasing.',
    'Explain masculine-leaning casual speech: roughness level, who uses it, and neutral/gentler alternatives.',
    {
      id: 'masculine-casual-tone',
      label: 'Masculine casual tone',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Masculine casual form; back rates roughness and gives neutral alternatives.',
      cardTemplates: [
        {
          label: 'Masculine casual',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nGloss: {meaning}\n\nTone: {nuance}\n\nNeutral alt: {culturalContext}',
          tags: ['ai-masc-casual'],
        },
      ],
    },
  ),
  preset(
    'casual-feminine',
    'Casual Feminine Speech',
    'specialized',
    'Softeners, sentence-final particles, and female-leaning casual phrasing.',
    'Explain feminine-leaning casual markers: particle choices, softness, and neutral alternatives without stereotyping.',
    {
      id: 'feminine-casual-tone',
      label: 'Feminine casual tone',
      profileId: 'p1-ja-focus',
      outputFormat: 'anki',
      description: 'Feminine-leaning casual form; back explains softening particles and neutral options.',
      cardTemplates: [
        {
          label: 'Feminine casual',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nGloss: {meaning}\n\nParticle/tone: {nuance}\n\nNeutral alt: {culturalContext}',
          tags: ['ai-fem-casual'],
        },
      ],
    },
  ),
  preset(
    'elderly-register',
    'Elderly / Archaic Speech',
    'specialized',
    'Older character voice, dated phrasing, and nostalgic diction.',
    'Explain elderly or dated speech patterns. Contrast with modern colloquial form and mark generational cues.',
    {
      id: 'elderly-speech-contrast',
      label: 'Elderly speech contrast',
      profileId: 'seed-ja-immersion',
      outputFormat: 'anki',
      description: 'Older-speaker phrasing; back contrasts modern equivalent and generational cues.',
      cardTemplates: [
        {
          label: 'Elderly register',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nModern equivalent: {meaning}\n\nGenerational cue: {culturalContext}',
          tags: ['ai-elderly'],
        },
      ],
    },
  ),
  preset(
    'child-speech',
    'Child Speech',
    'specialized',
    'Immature grammar, baby talk, and young character voice.',
    'Explain child speech errors or simplifications. Give adult-correct form and why the child form appears.',
    {
      id: 'child-speech-correction',
      label: 'Child speech correction',
      profileId: 'seed-context-cloze',
      outputFormat: 'anki',
      description: 'Child phrasing in dialogue; back shows adult form and error type.',
      cardTemplates: [
        {
          label: 'Child speech',
          front: '{expression}\n\n{sentence}',
          back: 'Adult form: {meaning}\n\nError/type: {grammarBreakdown}\n\nVoice note: {nuance}',
          tags: ['ai-child-speech'],
        },
      ],
    },
  ),
  preset(
    'regional-toponym',
    'Regional Place Nickname',
    'specialized',
    'Local nicknames, old province names, and micro-place references.',
    'Explain regional place nickname or micro-location. Map to modern admin names and local cultural association.',
    {
      id: 'regional-place-nickname',
      label: 'Regional place nickname',
      profileId: 'seed-chinese-bridge',
      outputFormat: 'anki',
      description: 'Regional place nickname; back maps to modern location and local association.',
      cardTemplates: [
        {
          label: 'Regional toponym',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\n{toponymNotes}\n\nModern map: {meaning}\n\nLocal note: {culturalContext}',
          tags: ['ai-regional-place'],
        },
      ],
    },
  ),
  preset(
    'surname-structure',
    'Surname / Name Structure',
    'specialized',
    'Kanji choices in names, readings, and naming conventions.',
    'Analyze surname/given name structure: kanji semantics, reading likelihood, naming trend, and character identity hints.',
    {
      id: 'name-kanji-structure',
      label: 'Name kanji structure',
      profileId: 'seed-kanji-front',
      outputFormat: 'anki',
      description: 'Name on kanji-first front; back explains kanji semantics and reading logic.',
      cardTemplates: [
        {
          label: 'Name structure',
          front: '{expression}\n\nWhat do the kanji suggest?',
          back: '{reading}\n\nKanji analysis: {properNameNotes}\n\nIdentity hints: {meaning}\n\nNotes: {nuance}',
          tags: ['ai-name-structure'],
        },
      ],
    },
  ),
  preset(
    'poetic-compression',
    'Poetic Compression',
    'specialized',
    'Haiku-like brevity, tanka fragments, and condensed literary lines.',
    'Unpack poetically compressed lines. Expand implicit subjects/objects and explain seasonal/wordplay compression.',
    {
      id: 'poetic-expansion',
      label: 'Poetic line expansion',
      profileId: 'seed-reading-first',
      outputFormat: 'anki',
      description: 'Compressed poetic line; back expands implicit grammar and imagery.',
      cardTemplates: [
        {
          label: 'Poetic compression',
          front: '{expression}\n\n{sentence}',
          back: 'Expanded reading: {meaning}\n\nImagery: {culturalContext}\n\nGrammar fill-in:\n{grammarBreakdown}',
          tags: ['ai-poetic'],
        },
      ],
    },
  ),
  preset(
    'manga-sfx',
    'Manga Sound Effect',
    'specialized',
    'SFX in katakana and action-line nonwords.',
    'Explain manga SFX: action depicted, English sound equivalent, and whether it is standard or author coinage.',
    {
      id: 'manga-sfx-action',
      label: 'Manga SFX action card',
      profileId: 'seed-image-mine',
      outputFormat: 'anki',
      description: 'SFX glyph; back describes depicted action and English sound mapping.',
      cardTemplates: [
        {
          label: 'Manga SFX',
          front: '{expression}\n\nWhat action/sound is this?',
          back: 'Action: {meaning}\n\nEnglish SFX: {nuance}\n\nScene: {culturalContext}',
          tags: ['ai-manga-sfx'],
        },
      ],
    },
  ),
  preset(
    'classical-grammar',
    'Classical Grammar (文語)',
    'specialized',
    'Classical endings, 已然形, and literary grammar outside modern school grammar.',
    'Explain classical/literary grammar forms. Give modern Japanese rewrite and identify classical ending/pattern.',
    {
      id: 'classical-modern-rewrite',
      label: 'Classical → modern rewrite',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Classical form in text; back gives modern rewrite and pattern name.',
      cardTemplates: [
        {
          label: 'Classical grammar',
          front: '{expression}\n\n{sentence}',
          back: 'Modern rewrite: {meaning}\n\nPattern:\n{grammarBreakdown}\n\nNotes: {nuance}',
          tags: ['ai-classical'],
        },
      ],
    },
  ),
  preset(
    'verb-aspect',
    'Verb Aspect / Nuance',
    'specialized',
    'Completion, ongoing state, try/attempt, and aspectual auxiliaries.',
    'Explain aspect nuance (start, finish, try, resultative). Compare with nearest alternative verb forms and result state.',
    {
      id: 'aspectual-contrast',
      label: 'Aspectual contrast',
      profileId: 'seed-en-n5',
      outputFormat: 'anki',
      description: 'Aspect-heavy verb form; back contrasts completion/ongoing/try readings.',
      cardTemplates: [
        {
          label: 'Verb aspect',
          front: '{expression}\n\n{sentence}',
          back: 'Aspect: {nuance}\n\nGloss: {meaning}\n\nCompare:\n{grammarBreakdown}',
          tags: ['ai-aspect'],
        },
      ],
    },
  ),
  preset(
    'particle-contrast',
    'Particle Contrast',
    'specialized',
    'は vs が, に vs で, へ vs に, and other high-friction particles.',
    'Focus on particle choice in this exact sentence. Explain why this particle fits and what would change with alternatives.',
    {
      id: 'particle-slot-test',
      label: 'Particle slot test',
      profileId: 'seed-context-cloze',
      outputFormat: 'anki',
      description: 'Sentence with particle focus; back explains slot semantics and wrong-particle effects.',
      cardTemplates: [
        {
          label: 'Particle contrast',
          front: '{expression}\n\n{sentence}\n\nWhy this particle here?',
          back: 'Slot analysis:\n{grammarBreakdown}\n\nMeaning shift: {nuance}\n\nGloss: {meaning}',
          tags: ['ai-particle'],
        },
      ],
    },
  ),
  preset(
    'conjugation-stack',
    'Conjugation Stack',
    'specialized',
    'Long verbal chains: causative-passive, compound auxiliaries, stacked negatives.',
    'Peel conjugation layers from outside in. Name each layer and give the dictionary lemma at the core.',
    {
      id: 'conjugation-layer-peel',
      label: 'Conjugation layer peel',
      profileId: 'seed-sentence-mine',
      outputFormat: 'anki',
      description: 'Stacked verb form; back peels layers from surface to dictionary lemma.',
      cardTemplates: [
        {
          label: 'Conjugation stack',
          front: '{expression}\n\n{sentence}',
          back: 'Layers (outer→inner):\n{grammarBreakdown}\n\nLemma gloss: {meaning}',
          tags: ['ai-conjugation'],
        },
      ],
    },
  ),
  preset(
    'loanword-shift',
    'Loanword Meaning Shift',
    'specialized',
    'Wasei-eigo and katakana words whose Japanese meaning diverges from English.',
    'Explain loanword false friends. Give source language word, actual Japanese meaning, and example collocations.',
    {
      id: 'loanword-false-friend',
      label: 'Loanword false friend',
      profileId: 'p2-en-ja',
      outputFormat: 'anki',
      description: 'Katakana loanword; back warns about EN false friend and gives true JP meaning.',
      cardTemplates: [
        {
          label: 'Loanword shift',
          front: '{expression}\n\nLooks English — what does it mean in Japanese?',
          back: '{reading}\n\nJP meaning: {meaning}\n\nEN false friend: {nuance}\n\nExamples: {culturalContext}',
          tags: ['ai-loanword'],
        },
      ],
    },
  ),
  preset(
    'kanji-etymology',
    'Kanji Etymology Hint',
    'specialized',
    'Semantic hints from kanji components for vocabulary memory.',
    'Give kanji composition mnemonic: core semantic components, misleading parts, and memory hook tied to meaning in this word.',
    {
      id: 'kanji-component-mnemonic',
      label: 'Kanji component mnemonic',
      profileId: 'seed-kanji-front',
      outputFormat: 'anki',
      description: 'Word with focus kanji; back gives component breakdown and mnemonic.',
      cardTemplates: [
        {
          label: 'Kanji etymology',
          front: '{expression}\n\nBreak down the kanji.',
          back: '{reading}\n\nComponents: {grammarBreakdown}\n\nMnemonic: {meaning}\n\nReading note: {nuance}',
          tags: ['ai-kanji'],
        },
      ],
    },
  ),
  preset(
    'ateji-reading',
    'Ateji / Irregular Reading',
    'specialized',
    'Irregular readings, jukujikun, and special name readings.',
    'Explain irregular reading type (jukujikun, ateji, name reading). List expected vs actual reading and similar traps.',
    {
      id: 'irregular-reading-trap',
      label: 'Irregular reading trap',
      profileId: 'seed-reading-first',
      outputFormat: 'anki',
      description: 'Irregular reading in context; back classifies reading type and common mistakes.',
      cardTemplates: [
        {
          label: 'Ateji / irregular reading',
          front: '{expression}\n\n{sentence}',
          back: 'Actual reading: {reading}\n\nType: {nuance}\n\nTrap note: {culturalContext}\n\nMeaning: {meaning}',
          tags: ['ai-ateji'],
        },
      ],
    },
  ),
  preset(
    'proverb-breakdown',
    'Proverb / 四字熟語',
    'specialized',
    'Four-character compounds and proverbial set phrases.',
    'Break proverb/yojijukugo into characters, literal image, and applied meaning in the sentence.',
    {
      id: 'proverb-yojijukugo',
      label: 'Proverb / yojijukugo card',
      profileId: 'seed-trilingual',
      outputFormat: 'csv',
      description: 'Set phrase on front; back gives character breakdown, image, and applied meaning.',
      cardTemplates: [
        {
          label: 'Proverb breakdown',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nCharacter breakdown:\n{grammarBreakdown}\n\nApplied meaning: {meaning}\n\nNuance: {nuance}',
          tags: ['ai-proverb'],
        },
      ],
    },
  ),
  preset(
    'emotion-affect',
    'Emotion / Affect Word',
    'specialized',
    'Fine-grained emotional vocabulary and attitude markers.',
    'Explain emotional nuance with intensity, valence, social acceptability, and nearest English/Russian emotion words.',
    {
      id: 'emotion-nuance-map',
      label: 'Emotion nuance map',
      profileId: 'seed-ru-examples',
      outputFormat: 'anki',
      description: 'Affect word in context; back maps intensity, valence, and translation options.',
      cardTemplates: [
        {
          label: 'Emotion affect',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nEmotion: {meaning}\n\nIntensity/valence: {nuance}\n\nRU/EN options: {sentenceTranslationRu}',
          tags: ['ai-emotion'],
        },
      ],
    },
  ),
  preset(
    'taboo-euphemism',
    'Taboo / Euphemism',
    'specialized',
    'Indirect references, softened terms, and censored topics.',
    'Explain euphemism or indirect reference: what is being avoided, blunt equivalent, and register sensitivity.',
    {
      id: 'euphemism-blunt-pair',
      label: 'Euphemism ↔ blunt pair',
      profileId: 'seed-minimal',
      outputFormat: 'anki',
      description: 'Euphemistic phrasing; back gives blunt equivalent and sensitivity notes.',
      cardTemplates: [
        {
          label: 'Taboo euphemism',
          front: '{expression}\n\n{sentence}',
          back: 'Indirect meaning: {meaning}\n\nBlunt equivalent: {nuance}\n\nSensitivity: {culturalContext}',
          tags: ['ai-euphemism'],
        },
      ],
    },
  ),
  preset(
    'character-voice',
    'Character Voice Marker',
    'specialized',
    'Catchphrases, verbal tics, and idiolect that marks a specific character.',
    'Explain how this phrasing marks character voice: tic type, frequency, social image, and translation preservation tips.',
    {
      id: 'character-catchphrase',
      label: 'Character catchphrase',
      profileId: 'seed-audio',
      outputFormat: 'anki',
      description: 'Character-specific phrase; back documents voice tic and translation preservation.',
      cardTemplates: [
        {
          label: 'Character voice',
          front: '{expression}\n\n{sentence}',
          back: 'Voice marker: {culturalContext}\n\nGloss: {meaning}\n\nPreserve as: {nuance}',
          tags: ['ai-character-voice'],
        },
      ],
    },
  ),
  preset(
    'frequency-rank',
    'Frequency / Rarity Context',
    'specialized',
    'Rare words worth mining because frequency lists flag them as uncommon.',
    'Explain why this token is worth mining despite or because of rarity. Summarize frequency signal and learning priority.',
    {
      id: 'frequency-priority',
      label: 'Frequency priority card',
      profileId: 'seed-frequency',
      outputFormat: 'anki',
      description: 'Rare token with frequency data; back explains rarity and mining priority.',
      cardTemplates: [
        {
          label: 'Frequency context',
          front: '{expression}\n\n{sentence}',
          back: '{reading}\n\nRanks: {frequency}\n\nGloss: {meaning}\n\nWhy mine this: {nuance}',
          tags: ['ai-frequency'],
        },
      ],
    },
  ),
  preset(
    'en-production-n2',
    'English → Japanese Production',
    'core',
    'Production drill from English definition to Japanese recall.',
    'Write production prompts where the front is an English definition or paraphrase and the back requires Japanese with reading.',
    {
      id: 'en-to-ja-production',
      label: 'EN definition → JA production',
      profileId: 'p2-en-ja',
      outputFormat: 'anki',
      description: 'English meaning on front; Japanese expression and reading on back.',
      cardTemplates: [
        {
          label: 'EN to JA production',
          front: '{meaning}\n\nSay it in Japanese.',
          back: '{expression}\n{reading}\n\n{sentence}\n\nNuance: {nuance}',
          tags: ['ai-production', 'en-ja'],
        },
      ],
    },
  ),
  preset(
    'ru-production',
    'Russian → Japanese Production',
    'core',
    'Production drill from Russian gloss to Japanese recall.',
    'Write production prompts where the front is a natural Russian paraphrase and the back reveals Japanese with reading.',
    {
      id: 'ru-to-ja-production',
      label: 'RU gloss → JA production',
      profileId: 'p3-ru-ja',
      outputFormat: 'anki',
      description: 'Russian gloss on front; Japanese expression and reading on back.',
      cardTemplates: [
        {
          label: 'RU to JA production',
          front: '{sentenceTranslationRu}\n\nКак по-японски?',
          back: '{expression}\n{reading}\n\n{sentence}\n\nEN: {meaning}',
          tags: ['ai-production', 'ru-ja'],
        },
      ],
    },
  ),
];

export const AI_PROMPT_PRESETS: readonly AiPromptPreset[] = CATALOG.map(
  ({ format: _format, ...presetDef }) => presetDef,
);

export const AI_MINING_FORMATS: readonly AiMiningCardFormat[] = CATALOG.map((entry) => entry.format);

export function formatsForPreset(presetId: string): AiMiningCardFormat[] {
  const matches = AI_MINING_FORMATS.filter((format) => format.presetId === presetId);
  return matches.length ? matches : AI_MINING_FORMATS.filter((format) => format.presetId === 'idiom-slang');
}
