/**
 * YouTube discovery — the console body for Phase 8 item 3.
 *
 * Composed into `DiscoverContent.tsx`'s existing panels rather than mounted as a
 * fourth page, so all three hosts of that console (the Scraper's Discover page,
 * Blanc's discover panel, and the Media Center's discover tab) get this surface
 * without any of them being edited.
 *
 * All judgement lives in `shared/youtubeDiscovery.ts`; this file renders it and
 * owns the two explicit user actions the feature has:
 *
 *   - **Check captions** — one `yt-dlp --skip-download` extraction for one
 *     video, which is the only way to learn whether a caption track was written
 *     by a person or generated by ASR.
 *   - **Add to playlist manager** — hands the video to `main/ytPlaylists.ts`,
 *     metadata only.
 *
 * Nothing here downloads media, and nothing here runs on mount: a search happens
 * when the user presses Search, and a probe happens when the user asks for one.
 */

import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import Icon from '../Icons';
import { useT } from '../../i18n';
import { parseSubtitles } from '../../subtitles';
import {
  CONSISTENT_CHANNEL_SHARE,
  deriveStudySignals,
  estimateSpeechRate,
  rankYoutubeCandidates,
  summariseChannelConsistency,
  youtubeCandidateId,
  type YoutubeChannelConsistency,
  type YoutubeDiscoveryCandidate,
  type YoutubeDiscoveryMode,
  type YoutubeFetchState,
  type YoutubeProbe,
  type YoutubeRanking,
  type YoutubeReason,
} from '../../../shared/youtubeDiscovery';
import type { StudyLevel } from '../../../shared/mediaDiscovery';
import {
  addToShortlist,
  loadYoutubeShortlist,
  onShortlistChanged,
  removeFromShortlist,
  type YoutubeShortlistEntry,
} from '../../discoveryShortlistStore';

/** The wire states, plus the two only a console has: nothing asked, and in flight. */
export type YoutubeLoadState = YoutubeFetchState | 'idle' | 'loading';
export type YoutubeView = 'results' | 'shortlist';

/** Per-video extras the console accumulates as the user asks for them. */
interface VideoInsight {
  probe?: YoutubeProbe;
  /** Target-script characters per minute, once a caption file has been read. */
  charsPerMinute?: number;
  /** The playlist-manager video id, once handed off. */
  managedVideoId?: string;
}

export interface YoutubeDiscoveryState {
  mode: YoutubeDiscoveryMode;
  setMode: (mode: YoutubeDiscoveryMode) => void;
  query: string;
  setQuery: (value: string) => void;
  submit: () => void;
  loadState: YoutubeLoadState;
  message: string;
  view: YoutubeView;
  setView: (view: YoutubeView) => void;
  results: YoutubeRanking[];
  channels: Map<string, YoutubeChannelConsistency>;
  selected: YoutubeRanking | null;
  select: (videoId: string | null) => void;
  insights: Record<string, VideoInsight>;
  busyVideoId: string | null;
  probe: (videoId: string) => void;
  handoff: (candidate: YoutubeDiscoveryCandidate) => void;
  measurePace: (candidate: YoutubeDiscoveryCandidate) => void;
  notice: string;
  /** The last "Check captions" that failed, and for which video. */
  probeError: { videoId: string; message: string } | null;
  shortlist: YoutubeShortlistEntry[];
  shortlistIds: Set<string>;
  toggleShortlist: (candidate: YoutubeDiscoveryCandidate) => void;
  requireHumanCaptions: boolean;
  setRequireHumanCaptions: (value: boolean) => void;
  hideLive: boolean;
  setHideLive: (value: boolean) => void;
}

const PREFS_KEY = 'jp-youtube-discovery-prefs-v1';

interface YoutubePrefs {
  mode: YoutubeDiscoveryMode;
  requireHumanCaptions: boolean;
  hideLive: boolean;
}

const DEFAULT_PREFS: YoutubePrefs = { mode: 'search', requireHumanCaptions: false, hideLive: true };

function readPrefs(): YoutubePrefs {
  try {
    const raw = localStorage.getItem(PREFS_KEY);
    if (!raw) return DEFAULT_PREFS;
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== 'object' || parsed === null) return DEFAULT_PREFS;
    const candidate = parsed as Partial<YoutubePrefs>;
    return {
      mode: candidate.mode === 'channel' ? 'channel' : 'search',
      requireHumanCaptions: candidate.requireHumanCaptions === true,
      hideLive: candidate.hideLive !== false,
    };
  } catch {
    return DEFAULT_PREFS;
  }
}

function writePrefs(prefs: YoutubePrefs): void {
  try {
    localStorage.setItem(PREFS_KEY, JSON.stringify(prefs));
  } catch {
    // Preferences are a convenience; losing them must never block the console.
  }
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useYoutubeDiscovery(level: StudyLevel, enabled = true): YoutubeDiscoveryState {
  const initial = useMemo(readPrefs, []);

  const [mode, setModeState] = useState<YoutubeDiscoveryMode>(initial.mode);
  const [query, setQuery] = useState('');
  const [candidates, setCandidates] = useState<YoutubeDiscoveryCandidate[]>([]);
  const [loadState, setLoadState] = useState<YoutubeLoadState>('idle');
  const [message, setMessage] = useState('');
  const [view, setView] = useState<YoutubeView>('results');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [insights, setInsights] = useState<Record<string, VideoInsight>>({});
  const [busyVideoId, setBusyVideoId] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  /** A "Check captions" that failed, said beside the video it was for (audit r2 #24). */
  const [probeError, setProbeError] = useState<{ videoId: string; message: string } | null>(null);
  const [shortlist, setShortlist] = useState<YoutubeShortlistEntry[]>([]);
  const [requireHumanCaptions, setRequireHumanCaptionsState] = useState(initial.requireHumanCaptions);
  const [hideLive, setHideLiveState] = useState(initial.hideLive);

  useEffect(() => {
    setShortlist(loadYoutubeShortlist());
    return onShortlistChanged(() => setShortlist(loadYoutubeShortlist()));
  }, []);

  const submit = useCallback(() => {
    const trimmed = query.trim();
    if (!trimmed || !enabled) return;
    setLoadState('loading');
    setMessage('');
    setView('results');
    const request = mode === 'channel'
      ? window.api?.ytDiscoveryChannel?.(trimmed)
      : window.api?.ytDiscoverySearch?.(trimmed);
    if (!request) {
      setLoadState('error');
      setMessage('');
      return;
    }
    void request
      .then((reply) => {
        setCandidates(reply.candidates ?? []);
        setMessage(reply.message ?? '');
        setLoadState(reply.state);
      })
      .catch((error: unknown) => {
        setCandidates([]);
        setMessage(error instanceof Error ? error.message : String(error));
        setLoadState('error');
      });
  }, [enabled, mode, query]);

  // Memoized rather than derived inline: `.map()` returns a fresh array every
  // render, which would make the three memos below recompute on every keystroke
  // in the search box.
  const source = useMemo(
    () => (view === 'shortlist' ? shortlist.map((entry) => entry.candidate) : candidates),
    [view, shortlist, candidates],
  );

  // Signals first, because channel consistency is computed *from* the signal set
  // and then fed back into scoring — a channel is only "consistent" relative to
  // what has actually been probed.
  const signalled = useMemo(
    () => source.map((candidate) => ({
      candidate,
      signals: deriveStudySignals(candidate, insights[candidate.videoId]?.probe ?? null, {
        target: 'ja',
        charsPerMinute: insights[candidate.videoId]?.charsPerMinute,
      }),
    })),
    [source, insights],
  );

  const channels = useMemo(() => {
    const rows = summariseChannelConsistency(signalled);
    return new Map(rows.map((row) => [row.channelId, row]));
  }, [signalled]);

  const results = useMemo(
    () => rankYoutubeCandidates(signalled, { level, consistency: channels, requireHumanCaptions, hideLive }),
    [signalled, level, channels, requireHumanCaptions, hideLive],
  );

  const selected = useMemo(
    () => results.find((entry) => entry.candidate.videoId === selectedId) ?? null,
    [results, selectedId],
  );

  const shortlistIds = useMemo(() => new Set(shortlist.map((entry) => entry.id)), [shortlist]);

  const setMode = useCallback((next: YoutubeDiscoveryMode) => {
    setModeState(next);
    writePrefs({ ...readPrefs(), mode: next });
  }, []);

  const setRequireHumanCaptions = useCallback((next: boolean) => {
    setRequireHumanCaptionsState(next);
    writePrefs({ ...readPrefs(), requireHumanCaptions: next });
  }, []);

  const setHideLive = useCallback((next: boolean) => {
    setHideLiveState(next);
    writePrefs({ ...readPrefs(), hideLive: next });
  }, []);

  const probe = useCallback((videoId: string) => {
    if (!window.api?.ytDiscoveryProbe) return;
    setBusyVideoId(videoId);
    setNotice('');
    setProbeError(null);
    void window.api.ytDiscoveryProbe(videoId)
      .then((reply) => {
        if (reply.probe) {
          setInsights((prev) => ({
            ...prev,
            [videoId]: { ...prev[videoId], probe: reply.probe ?? undefined },
          }));
        } else {
          setMessage(reply.message ?? '');
          setProbeError({ videoId, message: reply.message ?? '' });
          if (reply.state === 'tool-missing') setLoadState('tool-missing');
        }
      })
      .catch((error: unknown) =>
        setProbeError({ videoId, message: error instanceof Error ? error.message : String(error) }),
      )
      .finally(() => setBusyVideoId(null));
  }, []);

  const handoff = useCallback((candidate: YoutubeDiscoveryCandidate) => {
    if (!window.api?.ytAddVideoByUrl) return;
    setBusyVideoId(candidate.videoId);
    setNotice('');
    void window.api.ytAddVideoByUrl(candidate.url)
      .then((reply) => {
        if (reply.ok) {
          setInsights((prev) => ({
            ...prev,
            [candidate.videoId]: { ...prev[candidate.videoId], managedVideoId: reply.videoId },
          }));
        }
        setNotice(reply.ok ? 'handoffOk' : 'handoffFailed');
      })
      .catch(() => setNotice('handoffFailed'))
      .finally(() => setBusyVideoId(null));
  }, []);

  /**
   * Fetches the caption file for an already-handed-off video and measures pace.
   *
   * Two steps rather than one button that also adds the video: adding to the
   * playlist manager is a real change to the user's library and must not be a
   * side effect of asking a question about speech rate.
   */
  const measurePace = useCallback((candidate: YoutubeDiscoveryCandidate) => {
    const managedVideoId = insights[candidate.videoId]?.managedVideoId;
    const fetchSubs = window.api?.ytFetchSubsOnly;
    const readCaptions = window.api?.ytCachedCaptionText;
    if (!managedVideoId || !fetchSubs || !readCaptions) return;
    setBusyVideoId(candidate.videoId);
    setNotice('');
    void fetchSubs([managedVideoId])
      .then((reply) => {
        // A fetch main stopped at its deadline is not "no captions": say it
        // timed out, so a retry is the obvious next step.
        if (reply.results.some((result) => result.code === 'timeout')) {
          setNotice('paceTimedOut');
          return null;
        }
        return readCaptions(candidate.videoId);
      })
      .then((cached) => {
        if (!cached) return;
        const charsPerMinute = cached.text ? estimateSpeechRate(parseSubtitles(cached.text), 'ja') : undefined;
        if (typeof charsPerMinute !== 'number') {
          setNotice('paceUnavailable');
          return;
        }
        setInsights((prev) => ({
          ...prev,
          [candidate.videoId]: { ...prev[candidate.videoId], charsPerMinute },
        }));
      })
      .catch(() => setNotice('paceUnavailable'))
      .finally(() => setBusyVideoId(null));
  }, [insights]);

  const toggleShortlist = useCallback((candidate: YoutubeDiscoveryCandidate) => {
    const id = youtubeCandidateId(candidate);
    if (loadYoutubeShortlist().some((entry) => entry.id === id)) removeFromShortlist(id);
    else addToShortlist(candidate);
    setShortlist(loadYoutubeShortlist());
  }, []);

  const select = useCallback((videoId: string | null) => setSelectedId(videoId), []);

  return {
    mode,
    setMode,
    query,
    setQuery,
    submit,
    loadState,
    message,
    view,
    setView,
    results,
    channels,
    selected,
    select,
    insights,
    busyVideoId,
    probe,
    handoff,
    measurePace,
    notice,
    probeError,
    shortlist,
    shortlistIds,
    toggleShortlist,
    requireHumanCaptions,
    setRequireHumanCaptions,
    hideLive,
    setHideLive,
  };
}

// ---------------------------------------------------------------------------
// Presentation helpers
// ---------------------------------------------------------------------------

function scoreBand(score: number): 'high' | 'mid' | 'low' {
  if (score >= 70) return 'high';
  if (score >= 45) return 'mid';
  return 'low';
}

function formatDuration(seconds: number | undefined): string {
  if (typeof seconds !== 'number' || !Number.isFinite(seconds) || seconds <= 0) return '—';
  const total = Math.round(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (value: number): string => String(value).padStart(2, '0');
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

type Translate = (key: string, vars?: Record<string, string | number>) => string;

function reasonLabel(reason: YoutubeReason, t: Translate): string {
  switch (reason.code) {
    case 'captions-human':
      return t('ytDiscovery.reason.captionsHuman', { langs: reason.detail ?? '' });
    case 'captions-auto':
      return t('ytDiscovery.reason.captionsAuto');
    case 'captions-none':
      return t('ytDiscovery.reason.captionsNone');
    case 'captions-unchecked':
      return t('ytDiscovery.reason.captionsUnchecked');
    case 'audio-target':
      return t('ytDiscovery.reason.audioTarget');
    case 'audio-other':
      return t('ytDiscovery.reason.audioOther');
    case 'japanese-title':
      return t('ytDiscovery.reason.japaneseTitle');
    case 'pace-fit':
      return t('ytDiscovery.reason.paceFit', { rate: reason.detail ?? '' });
    case 'pace-fast':
      return t('ytDiscovery.reason.paceFast', { rate: reason.detail ?? '' });
    case 'pace-slow':
      return t('ytDiscovery.reason.paceSlow', { rate: reason.detail ?? '' });
    case 'length-fit':
      return t('ytDiscovery.reason.lengthFit');
    case 'length-long':
      return t('ytDiscovery.reason.lengthLong');
    case 'channel-consistent':
      return t('ytDiscovery.reason.channelConsistent', { ratio: reason.detail ?? '' });
    case 'is-live':
    default:
      return t('ytDiscovery.reason.isLive');
  }
}

/** The long form, for the inspector and for the row's accessible name. */
function captionLabel(entry: YoutubeRanking, t: Translate): string {
  switch (entry.signals.captions) {
    case 'human-target':
      return t('ytDiscovery.captions.humanTarget');
    case 'human-other':
      return t('ytDiscovery.captions.humanOther', { langs: entry.signals.humanCaptionLangs.join(', ') });
    case 'auto-only':
      return t('ytDiscovery.captions.autoOnly');
    case 'none':
      return t('ytDiscovery.captions.none');
    case 'unknown':
    default:
      return t('ytDiscovery.captions.unchecked');
  }
}

/** The short form for the fixed-width table column. */
function captionShort(entry: YoutubeRanking, t: Translate): string {
  switch (entry.signals.captions) {
    case 'human-target':
    case 'human-other':
      return t('ytDiscovery.captions.short.human');
    case 'auto-only':
      return t('ytDiscovery.captions.short.auto');
    case 'none':
      return t('ytDiscovery.captions.short.none');
    case 'unknown':
    default:
      return t('ytDiscovery.captions.short.unchecked');
  }
}

/**
 * The caption language badge. A language tag, not chrome, so it is shown
 * verbatim rather than translated — `ja` means the same thing in all four UI
 * languages, and `—` is an absence, not a word.
 */
function captionLangBadge(entry: YoutubeRanking): string {
  if (entry.signals.humanCaptionLangs.length > 0) return entry.signals.humanCaptionLangs.join('/');
  if (entry.signals.captions === 'unknown') return '?';
  return '—';
}

// ---------------------------------------------------------------------------
// Panels
// ---------------------------------------------------------------------------

export function YoutubeDiscoveryControls({ state }: { state: YoutubeDiscoveryState }) {
  const { t } = useT();
  const {
    mode, setMode, query, setQuery, submit, loadState,
    requireHumanCaptions, setRequireHumanCaptions, hideLive, setHideLive,
  } = state;

  return (
    <div className="disc-controls">
      <div className="disc-searchline">
        <div className="disc-searchbox">
          <Icon name="search" size={13} />
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => {
              // Enter confirms an IME conversion; it must not search yet.
              if (e.nativeEvent.isComposing || e.nativeEvent.keyCode === 229) return;
              if (e.key === 'Enter') submit();
            }}
            placeholder={t(mode === 'channel'
              ? 'ytDiscovery.search.placeholderChannel'
              : 'ytDiscovery.search.placeholder')}
            aria-label={t('ytDiscovery.search.label')}
          />
        </div>
        <button
          type="button"
          className="disc-btn disc-btn-primary"
          onClick={submit}
          disabled={!query.trim() || loadState === 'loading'}
        >
          {t('ytDiscovery.search.run')}
        </button>
      </div>

      <div className="disc-filterline">
        <div className="disc-segment" role="group" aria-label={t('ytDiscovery.mode.label')}>
          {(['search', 'channel'] as const).map((id) => (
            <button
              key={id}
              type="button"
              className={`disc-seg-btn ${mode === id ? 'active' : ''}`}
              aria-pressed={mode === id}
              onClick={() => setMode(id)}
            >
              {t(`ytDiscovery.mode.${id}`)}
            </button>
          ))}
        </div>

        <label className="disc-check">
          <input
            type="checkbox"
            checked={requireHumanCaptions}
            onChange={(e) => setRequireHumanCaptions(e.target.checked)}
          />
          <span>{t('ytDiscovery.filter.humanCaptions')}</span>
        </label>

        <label className="disc-check">
          <input type="checkbox" checked={hideLive} onChange={(e) => setHideLive(e.target.checked)} />
          <span>{t('ytDiscovery.filter.hideLive')}</span>
        </label>
      </div>
    </div>
  );
}

export function YoutubeDiscoveryResults({ state }: { state: YoutubeDiscoveryState }) {
  const { t } = useT();
  const {
    results, selected, select, loadState, message, view, setView,
    shortlistIds, toggleShortlist, shortlist, busyVideoId, probe,
  } = state;

  const header = (
    <div className="disc-tabs" role="tablist">
      <button
        type="button"
        role="tab"
        aria-selected={view === 'results'}
        className={`disc-tab ${view === 'results' ? 'active' : ''}`}
        onClick={() => setView('results')}
      >
        {t('ytDiscovery.view.results')}
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={view === 'shortlist'}
        className={`disc-tab ${view === 'shortlist' ? 'active' : ''}`}
        onClick={() => setView('shortlist')}
      >
        {t('ytDiscovery.view.shortlist')}
        {shortlist.length > 0 ? <span className="disc-tab-count">{shortlist.length}</span> : null}
      </button>
    </div>
  );

  let body: ReactNode;
  if (view === 'results' && loadState === 'loading') {
    body = <div className="disc-placeholder">{t('ytDiscovery.state.loading')}</div>;
  } else if (view === 'results' && loadState === 'tool-missing') {
    // The "not configured" state. This feature has no API key to be missing —
    // the only thing it can lack is the binary it shares with the downloader.
    body = (
      <div className="disc-placeholder disc-placeholder-error">
        {t('ytDiscovery.state.toolMissing')}
      </div>
    );
  } else if (view === 'results' && loadState === 'error') {
    body = (
      <div className="disc-placeholder disc-placeholder-error">
        {t('ytDiscovery.state.error')}{message ? ` — ${message}` : ''}
      </div>
    );
  } else if (view === 'results' && loadState === 'idle') {
    body = <div className="disc-placeholder">{t('ytDiscovery.state.idle')}</div>;
  } else if (results.length === 0) {
    body = (
      <div className="disc-placeholder">
        {view === 'shortlist' ? t('ytDiscovery.state.shortlistEmpty') : t('ytDiscovery.state.empty')}
      </div>
    );
  } else {
    body = (
      <div className="disc-table" role="table" aria-label={t('ytDiscovery.results.label')}>
        {/* Eight cells per row, matching `.disc-row`'s fixed grid. */}
        <div className="disc-row disc-row-head" role="row">
          <span>{t('scraper.column.rank')}</span>
          <span>{t('scraper.column.title')}</span>
          <span>{t('ytDiscovery.column.study')}</span>
          <span>{t('ytDiscovery.column.lang')}</span>
          <span>{t('ytDiscovery.column.captions')}</span>
          <span>{t('ytDiscovery.column.audio')}</span>
          <span>{t('ytDiscovery.column.length')}</span>
          <span />
        </div>
        {results.map((entry, index) => {
          const id = youtubeCandidateId(entry.candidate);
          const shortlisted = shortlistIds.has(id);
          const busy = busyVideoId === entry.candidate.videoId;
          return (
            <div
              key={id}
              role="row"
              className={`disc-row ${selected?.candidate.videoId === entry.candidate.videoId ? 'selected' : ''}`}
              onClick={() => select(entry.candidate.videoId)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  select(entry.candidate.videoId);
                }
              }}
              tabIndex={0}
            >
              <span className="disc-cell-rank">{index + 1}</span>
              <span className="disc-cell-title">
                <strong>{entry.candidate.title}</strong>
                {entry.candidate.channelTitle ? <small>{entry.candidate.channelTitle}</small> : null}
              </span>
              <span className="disc-cell-match">
                <span className={`disc-meter disc-meter-${scoreBand(entry.studyScore)}`}>
                  <span style={{ width: `${entry.studyScore}%` }} />
                </span>
                <em>{Math.round(entry.studyScore)}</em>
              </span>
              <span className="disc-cell-level">
                <span className="disc-badge" title={captionLabel(entry, t)}>
                  {captionLangBadge(entry)}
                </span>
              </span>
              <span className="disc-cell-dim">{captionShort(entry, t)}</span>
              <span className="disc-cell-dim">{t(`ytDiscovery.audio.${entry.signals.audio}`)}</span>
              <span className="disc-cell-dim">{formatDuration(entry.candidate.durationSec)}</span>
              <span className="disc-cell-action">
                <button
                  type="button"
                  className="disc-pin"
                  disabled={busy || entry.probed}
                  title={t('ytDiscovery.action.probe')}
                  aria-label={t('ytDiscovery.action.probeRow', { title: entry.candidate.title })}
                  onClick={(e) => {
                    e.stopPropagation();
                    select(entry.candidate.videoId);
                    probe(entry.candidate.videoId);
                  }}
                >
                  <Icon name="search" size={12} />
                </button>
                <button
                  type="button"
                  className={`disc-pin ${shortlisted ? 'active' : ''}`}
                  title={shortlisted ? t('scraper.action.unshortlist') : t('scraper.action.shortlist')}
                  aria-label={t(
                    shortlisted ? 'scraper.action.unshortlistRow' : 'scraper.action.shortlistRow',
                    { title: entry.candidate.title },
                  )}
                  aria-pressed={shortlisted}
                  onClick={(e) => {
                    e.stopPropagation();
                    toggleShortlist(entry.candidate);
                  }}
                >
                  <Icon name="bookmark" size={12} />
                </button>
              </span>
            </div>
          );
        })}
      </div>
    );
  }

  return (
    <div className="disc-youtube">
      {header}
      {body}
    </div>
  );
}

export function YoutubeDiscoveryInspector({ state }: { state: YoutubeDiscoveryState }) {
  const { t } = useT();
  const {
    selected, insights, busyVideoId, probe, handoff, measurePace,
    notice, probeError, shortlistIds, toggleShortlist, channels,
  } = state;

  // Sort only — every label below is resolved through `t()` down in the JSX, so
  // the list re-renders in the new language on a switch without this memo
  // knowing about the language at all. (A memo that *did* build strings would
  // need `lang` in its deps, never `t`, whose identity is stable by design.)
  const reasons = useMemo(
    () => (selected ? [...selected.reasons].sort((a, b) => b.points - a.points) : []),
    [selected],
  );

  if (!selected) {
    return (
      <aside className="disc-inspector disc-inspector-empty" aria-label={t('ytDiscovery.inspector.label')}>
        <p>{t('ytDiscovery.inspector.hint')}</p>
      </aside>
    );
  }

  const { candidate, signals } = selected;
  const insight = insights[candidate.videoId] ?? {};
  const busy = busyVideoId === candidate.videoId;
  const shortlisted = shortlistIds.has(youtubeCandidateId(candidate));
  const channel = channels.get(candidate.channelId || candidate.channelTitle || '');

  return (
    <aside className="disc-inspector" aria-label={t('ytDiscovery.inspector.label')}>
      <div className="disc-insp-head">
        {candidate.thumbUrl ? (
          <img src={candidate.thumbUrl} alt="" loading="lazy" referrerPolicy="no-referrer" />
        ) : (
          <div className="disc-insp-noart"><Icon name="image" size={18} /></div>
        )}
        <div>
          <h2>{candidate.title}</h2>
          {candidate.channelTitle ? <p className="disc-insp-native">{candidate.channelTitle}</p> : null}
          <p className="disc-insp-meta">{formatDuration(candidate.durationSec)}</p>
        </div>
      </div>

      <div className="disc-insp-score">
        <span className={`disc-meter disc-meter-${scoreBand(selected.studyScore)}`}>
          <span style={{ width: `${selected.studyScore}%` }} />
        </span>
        <strong>{Math.round(selected.studyScore)}</strong>
        <small>{t('ytDiscovery.inspector.studyScore')}</small>
      </div>

      <section className="disc-insp-block">
        <h3>{t('ytDiscovery.inspector.signals')}</h3>
        <ul className="disc-reasons">
          <li>
            <span>{t('ytDiscovery.signal.captions')}</span>
            <em>{captionLabel(selected, t)}</em>
          </li>
          <li>
            <span>{t('ytDiscovery.signal.audio')}</span>
            <em>{t(`ytDiscovery.audio.${signals.audio}`)}</em>
          </li>
          <li>
            <span>{t('ytDiscovery.signal.pace')}</span>
            <em>
              {signals.pace === 'unknown'
                ? t('ytDiscovery.pace.unknown')
                : t(`ytDiscovery.pace.${signals.pace}`, {
                  rate: Math.round(signals.charsPerMinute ?? 0),
                })}
            </em>
          </li>
          {channel && channel.humanCaptionShare !== null ? (
            <li>
              <span>{t('ytDiscovery.signal.channel')}</span>
              <em>
                {t(
                  channel.humanCaptionShare >= CONSISTENT_CHANNEL_SHARE
                    ? 'ytDiscovery.channel.consistent'
                    : 'ytDiscovery.channel.mixed',
                  // `count` is the plural selector the catalogs key on, so the
                  // probed sample — not the caption hits — has to be the one
                  // named `count`, or Russian inflects on the wrong number.
                  { count: channel.probed, withCaptions: channel.withHumanTargetCaptions },
                )}
              </em>
            </li>
          ) : null}
        </ul>
        <p className="disc-insp-note">{t('ytDiscovery.inspector.estimateNote')}</p>
      </section>

      <section className="disc-insp-block">
        <h3>{t('scraper.inspector.why')}</h3>
        <ul className="disc-reasons">
          {reasons.map((reason) => (
            <li key={reason.code} className={reason.points < 0 ? 'negative' : ''}>
              <span>{reasonLabel(reason, t)}</span>
              <em>{reason.points > 0 ? `+${reason.points}` : reason.points}</em>
            </li>
          ))}
        </ul>
      </section>

      {notice ? <p className="disc-insp-note" role="status">{t(`ytDiscovery.notice.${notice}`)}</p> : null}
      {probeError && probeError.videoId === candidate.videoId ? (
        <p className="disc-insp-note disc-insp-error" role="alert">
          {probeError.message
            ? t('ytDiscovery.notice.probeFailedDetail', { detail: probeError.message })
            : t('ytDiscovery.notice.probeFailed')}
        </p>
      ) : null}

      <div className="disc-insp-actions">
        <button
          type="button"
          className="disc-btn disc-btn-primary"
          disabled={busy || selected.probed}
          onClick={() => probe(candidate.videoId)}
        >
          <Icon name="search" size={12} />
          {selected.probed ? t('ytDiscovery.action.probed') : t('ytDiscovery.action.probe')}
        </button>
        <button
          type="button"
          className="disc-btn"
          disabled={busy || Boolean(insight.managedVideoId)}
          onClick={() => handoff(candidate)}
        >
          <Icon name="library" size={12} />
          {insight.managedVideoId ? t('ytDiscovery.action.added') : t('ytDiscovery.action.addToManager')}
        </button>
        <button
          type="button"
          className="disc-btn"
          disabled={busy || !insight.managedVideoId || typeof insight.charsPerMinute === 'number'}
          title={insight.managedVideoId ? undefined : t('ytDiscovery.action.measurePaceHint')}
          onClick={() => measurePace(candidate)}
        >
          <Icon name="headphones" size={12} />
          {t('ytDiscovery.action.measurePace')}
        </button>
        <button
          type="button"
          className="disc-btn"
          onClick={() => toggleShortlist(candidate)}
        >
          <Icon name="bookmark" size={12} />
          {shortlisted ? t('scraper.action.unshortlist') : t('scraper.action.shortlist')}
        </button>
        <button
          type="button"
          className="disc-btn"
          onClick={() => void window.api?.openExternal?.(candidate.url)}
        >
          <Icon name="external" size={12} />
          {t('ytDiscovery.action.openOnYoutube')}
        </button>
      </div>
    </aside>
  );
}
