/**
 * Canonical grammar-function label set (deduped from the legacy function list).
 *
 * The source list shipped ~180 labels containing true synonym pairs — e.g.
 * "What did not match the prediction" / "What does not match the prediction",
 * "Emphasize negative meaning" / "Emphasize the negative". Left alone those
 * scatter identical points across synonym buckets, which is the failure mode
 * this rebuild exists to remove. MERGES below folds each synonym into one
 * canonical id; old ids stay resolvable so imported data and saved user
 * filters keep working.
 *
 * `hint` is shown to the classifier, not the user — it disambiguates buckets a
 * 1.7B model would otherwise confuse (e.g. Limit vs Extremes).
 */

/** canonical id -> { label, hint } */
const CANONICAL = {
  surprise: { label: 'Surprise', hint: 'astonishment at an unexpected fact' },
  ratio: { label: 'Ratio', hint: 'rate, percentage, proportion of a whole' },
  compare: { label: 'Compare', hint: 'comparing two things (より, ほど)' },
  criticize: { label: 'Criticize', hint: 'blaming or faulting someone' },
  exclamatory: { label: 'Exclamatory', hint: 'emotional exclamation (なんて, とは)' },
  grounds: { label: 'Grounds', hint: 'basis or evidence for a claim (からには, 上は)' },
  'cause-reason': { label: 'Cause/reason', hint: 'because, since (から, ので, ため)' },
  'cause-time-relationship': { label: 'Cause/time relationship', hint: 'cause tied to a moment in time' },
  feel: { label: 'Feel', hint: 'sensation or impression (気がする)' },
  affection: { label: 'Affection', hint: 'fondness, endearment' },
  'action-status': { label: 'Action/status', hint: 'state resulting from an action (てある, ておく)' },
  finish: { label: 'Finish', hint: 'completing or finishing an action (てしまう, 終わる)' },
  'action-effort': { label: 'Action/effort', hint: 'trying or making an effort (てみる, ようとする)' },
  emphasize: { label: 'Emphasize', hint: 'general emphasis (こそ, さえ)' },
  extremes: { label: 'Extremes', hint: 'the utmost degree (きわまる, の極み)' },
  'extreme-example': { label: 'Extreme example', hint: 'even X, of all things (すら, まで)' },
  simultaneous: { label: 'Simultaneous', hint: 'two things at once (ながら, と同時に)' },
  process: { label: 'Process', hint: 'ongoing progression (つつある)' },
  proportional: { label: 'Proportional', hint: 'the more X the more Y (ば〜ほど, につれて)' },
  limit: { label: 'Limit', hint: 'only, nothing but (だけ, しか, ばかり)' },
  'denote-by-example': { label: 'Denote by example', hint: 'citing an example (とか, など, たとえば)' },
  time: { label: 'Time', hint: 'plain point in time (とき)' },
  invariant: { label: 'Invariant', hint: 'unchanging regardless of anything (をとわず)' },
  'perspective-way': { label: 'Perspective/way', hint: 'viewpoint or standpoint (にとって, から見ると)' },
  act: { label: 'Act', hint: 'performing an act' },
  'time-situation': { label: 'Time/situation', hint: 'circumstance-bound timing (際に, にあたって)' },
  ability: { label: 'Ability', hint: 'can / potential (られる, ことができる)' },
  'unexpected-outcome': { label: 'What did not match the prediction', hint: 'contrary to expectation (のに, はずが)' },
  'purpose-goal': { label: 'Purpose/goal', hint: 'in order to (ため, ように, には)' },
  direction: { label: 'Direction', hint: 'directional movement (へ, 向かって)' },
  'similarity-degree': { label: 'Similarity/degree', hint: 'like, as if (よう, みたい, らしい)' },
  'location-method-cause': { label: 'Location/method/cause', hint: 'the particle で and its senses' },
  'time-direction': { label: 'Time/direction', hint: 'from/until a time (から, まで)' },
  companion: { label: 'Companion', hint: 'together with (と, とともに)' },
  'point-of-departure-receipt': { label: 'Point of departure/receipt', hint: 'origin and end point (から〜まで)' },
  contrast: { label: 'Contrast', hint: 'X but Y (が, けど, 一方)' },
  range: { label: 'Range', hint: 'scope or extent covered (にわたって)' },
  'emphasize-negative': { label: 'Emphasize negative meaning', hint: 'strong negation (どころか, まったく〜ない)' },
  level: { label: 'Level', hint: 'degree or standard reached (ほど, くらい)' },
  'invite-suggest': { label: 'Invite/suggest', hint: 'inviting or proposing (ましょう, ませんか)' },
  status: { label: 'Status', hint: 'a state of being' },
  amount: { label: 'Amount', hint: 'quantity, including approximate amounts' },
  frequency: { label: 'Frequency', hint: 'how often (たびに, ごとに)' },
  wish: { label: 'Wish', hint: 'wishing or hoping (といい, ように)' },
  'necessary-obligation': { label: 'Necessary/obligation', hint: 'must, have to (なければならない, べき)' },
  definition: { label: 'Definition', hint: 'defining what something is (とは)' },
  desire: { label: 'Desire', hint: 'wanting (たい, ほしい)' },
  speculation: { label: 'Speculation', hint: 'guessing, inferring (だろう, かもしれない, らしい)' },
  confirm: { label: 'Confirm', hint: 'seeking confirmation (ね, でしょう)' },
  judge: { label: 'Judge', hint: 'evaluating or judging (べきだ, にすぎない)' },
  intent: { label: 'Intent', hint: 'will or intention (つもり, う/よう)' },
  plan: { label: 'Plan', hint: 'scheduled plan (ことになる, 予定)' },
  allow: { label: 'Allow', hint: 'permission, approval (てもいい)' },
  benefit: { label: 'Benefit', hint: 'giving/receiving a favour (てくれる, てもらう)' },
  'conjugated-from': { label: 'Conjugated from', hint: 'a conjugation-derived form' },
  order: { label: 'Order', hint: 'commands (なさい, ろ)' },
  'emphasize-on-level': { label: 'Emphasize on the level', hint: 'emphasis about degree' },
  asked: { label: 'Asked', hint: 'reported question' },
  explain: { label: 'Explain', hint: 'explanatory (のだ, わけだ)' },
  'relationships-in-time': { label: 'Relationships in time', hint: 'temporal relation between events' },
  decision: { label: 'Decision', hint: 'deciding (ことにする, に決める)' },
  condition: { label: 'Condition', hint: 'general if (ば, たら, と, なら)' },
  'condition-requirement': { label: 'Condition (requirement)', hint: 'necessary/sufficient condition (さえ〜ば)' },
  'condition-assumption': { label: 'Condition (assumption)', hint: 'supposing that (としたら, とすれば)' },
  'condition-contrary': { label: 'Condition (contrary to reality)', hint: 'counterfactual (ば〜のに, たら〜のに)' },
  achievement: { label: 'Achievement', hint: 'reaching or attaining' },
  'time-sequence': { label: 'Time/sequence', hint: 'ordering of events (てから, あとで, 前に)' },
  characteristics: { label: 'Characteristics', hint: 'traits of a thing (っぽい, がち)' },
  'comes-next': { label: 'Comes next', hint: 'what follows next' },
  'past-state': { label: 'The past/state', hint: 'a former state ( te-form + いた)' },
  regret: { label: 'Regret', hint: 'regret or remorse (ばよかった)' },
  continuity: { label: 'Continuity', hint: 'continuing (つづける, ままで)' },
  heard: { label: 'Heard', hint: 'hearsay / information source (そうだ, という)' },
  case: { label: 'Case', hint: 'in the case of (場合)' },
  negative: { label: 'Negative', hint: 'plain negation (ない, ません)' },
  'negative-in-the-past': { label: 'Negative in the past', hint: 'past negation' },
  conclude: { label: 'Conclude', hint: 'drawing a conclusion (わけだ, ということだ)' },
  add: { label: 'Add', hint: 'in addition (うえに, ばかりでなく)' },
  assumptions: { label: 'Assumptions', hint: 'premise taken as given (上で, 前提)' },
  remind: { label: 'Remind', hint: 'recalling or reminding' },
  standard: { label: 'Standard', hint: 'a criterion or basis (によって, に基づいて)' },
  'time-space': { label: 'Time/space', hint: 'spatial-temporal extent' },
  place: { label: 'Place', hint: 'location (で, において)' },
  'short-time': { label: 'Short time', hint: 'a brief interval (うちに, とたん)' },
  'results-state': { label: 'Results state', hint: 'resulting condition (ことになっている)' },
  result: { label: 'Result', hint: 'outcome of an action (結果, あげく)' },
  as: { label: 'As', hint: 'in the capacity of (として)' },
  passive: { label: 'Passive', hint: 'passive voice (られる)' },
  refuse: { label: 'Refuse', hint: 'refusal or rejection' },
  'much-less-on-level': { label: 'Much less on the level', hint: 'let alone, still less (はもちろん, どころか)' },
  adjective: { label: 'Adjective', hint: 'adjectival form or usage' },
  'means-methods': { label: 'Means/methods', hint: 'by means of (によって, で)' },
  'queue-listing': { label: 'Queue/listing', hint: 'listing items (たり, し)' },
  'how-to-say-the-first': { label: 'How to say the first', hint: 'first of all (まず)' },
  'reverent-humble': { label: 'Reverent/humble', hint: 'keigo, honorific or humble' },
  'relationships-follow': { label: 'Relationships follow', hint: 'consequential relation between parties' },
  'story-topic': { label: 'Story topic', hint: 'introducing or shifting topic (といえば, ば)' },
  selective: { label: 'Selective', hint: 'choosing between options (か, または)' },
  speak: { label: 'Speak', hint: 'manner of speaking' },
  ban: { label: 'Ban', hint: 'prohibition (てはいけない, な)' },
  'repeat-habits': { label: 'Repeat/habits', hint: 'habitual action (ものだ, ことがある)' },
  'request-permission': { label: 'Request permission', hint: 'asking to be allowed (てもいいですか)' },
  request: { label: 'Request', hint: 'asking someone to do something (てください, てほしい)' },
  vague: { label: 'Vague', hint: 'hedging or vagueness (とか, なんか)' },
  concessions: { label: 'Concessions', hint: 'even if, although (ても, のに, ながらも)' },
  'change-the-way': { label: 'Change the way you say it', hint: 'rephrasing or correcting' },
  'of-course': { label: 'Of course', hint: 'naturally, as expected (はずだ, に決まっている)' },
  innocent: { label: 'Innocent', hint: 'blamelessness' },
  trend: { label: 'Trend', hint: 'tendency (がちだ, 傾向がある)' },
  exception: { label: 'Exception', hint: 'except for (をのぞいて, 以外)' },
  value: { label: 'Value', hint: 'worth or merit (かいがある, 価値)' },
  'related-respectively': { label: 'Related/respectively', hint: 'each respectively (それぞれ)' },
  'arguments-affirmative': { label: 'Arguments (affirmative)', hint: 'affirming an argument' },
  forced: { label: 'Forced', hint: 'causative / being made to (させる)' },
  advice: { label: 'Advice', hint: 'recommending (たほうがいい, べき)' },
  describe: { label: 'Describe', hint: 'describing a thing or scene' },
  'highest-level': { label: 'Highest level', hint: 'the very top (最も, 一番)' },
  experience: { label: 'Experience', hint: 'having done before (たことがある)' },
  give: { label: 'Give', hint: 'giving (あげる, くれる)' },
  period: { label: 'Period', hint: 'a span of time (間, 中)' },
  attach: { label: 'Attach', hint: 'attaching or appending' },
  warning: { label: 'Warning', hint: 'caution (ないように, おそれがある)' },
  situation: { label: 'Situation', hint: 'circumstances (状況, 場合)' },
  'immediately-after': { label: 'Immediately after', hint: 'right after (とたん, next いなや)' },
  'shortly-before': { label: 'Shortly before', hint: 'just before (直前, ところだった)' },
  through: { label: 'Through', hint: 'via, throughout (を通じて, を通して)' },
  halfway: { label: 'Halfway', hint: 'partway through (かけ, 途中)' },
  contemptuous: { label: 'Contemptuous', hint: 'disdain or scorn' },
  'future-time': { label: 'Future time', hint: 'a future point in time' },
};

/**
 * Retired id -> canonical id. Every one of these is a synonym or a strict
 * subset of its target; keeping them resolvable means saved filters and the
 * existing corpus tags do not break.
 */
const MERGES = {
  // synonym pairs from the source list
  unexpected: 'unexpected-outcome',
  'emphasize-the-negative': 'emphasize-negative',
  'conditions-contrary-to-reality': 'condition-contrary',
  'determination-decision': 'decision',
  'determination-decisive': 'decision',
  'invite-advise': 'invite-suggest',
  'invite-to-invite': 'invite-suggest',
  suggest: 'invite-suggest',
  'condition-general': 'condition',
  'condition-sufficient': 'condition-requirement',
  'compare-contrast': 'compare',
  'state-contrast': 'contrast',
  'limit-extreme': 'limit',
  'rate-parallel': 'ratio',
  'percentage-parallel': 'ratio',
  described: 'describe',
  'description-explanation': 'explain',
  'purpose-target': 'purpose-goal',
  'purpose-nouns': 'purpose-goal',
  'status-action': 'action-status',
  orders: 'order',
  'order-definition': 'definition',
  method: 'means-methods',
  'represented-by-example': 'denote-by-example',
  'for-example': 'denote-by-example',
  'request-suggestion': 'request',
  'at-the-same-time': 'simultaneous',
  'space-relations': 'time-space',
  similarities: 'similarity-degree',
  aspiration: 'wish',
  'levels-are-few': 'much-less-on-level',
  'much-less-volume': 'much-less-on-level',
  'willpower-intention': 'intent',
  'planning-rules': 'plan',
  listed: 'queue-listing',
  obligatory: 'necessary-obligation',
  completed: 'finish',
  reaching: 'achievement',
  evaluate: 'judge',
  'approve-agree': 'allow',
  deductive: 'speculation',
  premise: 'assumptions',
  'taste-point-of-view': 'perspective-way',
  'origin-and-end-point': 'point-of-departure-receipt',
  'starting-point': 'point-of-departure-receipt',
  'relationships-behind': 'relationships-follow',
  'transfer-the-story': 'story-topic',
  'communication-skillful': 'speak',
  'information-resource': 'heard',
  'amount-roughly': 'amount',
  modify: 'change-the-way',
  corrections: 'change-the-way',
  'as-expected': 'of-course',
  expected: 'of-course',
  blame: 'criticize',
  // the bucket this whole rebuild exists to eliminate
  other: null,
};

const CANONICAL_IDS = Object.keys(CANONICAL);

/** Resolve any historical id to its canonical id, or null if retired. */
function resolve(id) {
  if (CANONICAL[id]) return id;
  if (id in MERGES) return MERGES[id];
  return null;
}

module.exports = { CANONICAL, CANONICAL_IDS, MERGES, resolve };
