/**
 * Companion chatter and built-in buddy routine text in the UI language.
 *
 * dialoguePools.ts and buddyRoutines.ts keep their English lines as the source
 * (a routine is saved into the environment settings with its text, and a user
 * may edit it). Anything that is still exactly a built-in English line is shown
 * through its catalogue key; text the user typed is shown as typed.
 */
import { t } from '../i18n';

const BUILTIN_TEXT: Record<string, string> = {
  'Ready when you are.': 'companion.line.studyBuddy.idle.1',
  'Shall we review?': 'companion.line.studyBuddy.idle.2',
  'I brought flashcards.': 'companion.line.studyBuddy.idle.3',
  'Good morning — warm-up cards?': 'companion.line.studyBuddy.morning.1',
  'Sunlight and kanji.': 'companion.line.studyBuddy.morning.2',
  'Afternoon focus!': 'companion.line.studyBuddy.afternoon.1',
  'One more page?': 'companion.line.studyBuddy.afternoon.2',
  'Evening review time.': 'companion.line.studyBuddy.evening.1',
  'Wind down with a deck.': 'companion.line.studyBuddy.evening.2',
  'Late session? I am with you.': 'companion.line.studyBuddy.night.1',
  'Quiet study hours.': 'companion.line.studyBuddy.night.2',
  'Nice beat for vocab.': 'companion.line.studyBuddy.music.1',
  'I can keep rhythm.': 'companion.line.studyBuddy.music.2',
  'Nice reading streak.': 'companion.line.studyBuddy.study.1',
  'That sentence was solid.': 'companion.line.studyBuddy.study.2',
  'Card cleared!': 'companion.line.studyBuddy.flashcard.1',
  'Keep going.': 'companion.line.studyBuddy.flashcard.2',
  'Level up! You earned that.': 'companion.line.studyBuddy.levelUp.1',
  'Stronger every day.': 'companion.line.studyBuddy.levelUp.2',
  'Hi!': 'companion.line.studyBuddy.click.1',
  'Let’s study.': 'companion.line.studyBuddy.click.2',
  'Tap me anytime.': 'companion.line.studyBuddy.click.3',
  'Sniff sniff…': 'companion.line.critter.idle.1',
  'What’s over there?': 'companion.line.critter.idle.2',
  'Boop.': 'companion.line.critter.idle.3',
  'Morning stretch!': 'companion.line.critter.morning.1',
  'Floor feels warm.': 'companion.line.critter.morning.2',
  'Curling up…': 'companion.line.critter.night.1',
  'Zzz… almost.': 'companion.line.critter.night.2',
  'Dance paws!': 'companion.line.critter.music.1',
  'Wiggle wiggle.': 'companion.line.critter.music.2',
  'You read; I explore.': 'companion.line.critter.study.1',
  'Found a dust bunny.': 'companion.line.critter.study.2',
  'You leveled! Bounce!': 'companion.line.critter.levelUp.1',
  'Sparkles!': 'companion.line.critter.levelUp.2',
  'Hey!': 'companion.line.critter.click.1',
  'Pet? Okay.': 'companion.line.critter.click.2',
  'Tick.': 'companion.line.timekeeper.idle.1',
  'Still on schedule.': 'companion.line.timekeeper.idle.2',
  'Watching the clock.': 'companion.line.timekeeper.idle.3',
  'Good morning.': 'companion.line.timekeeper.morning.1',
  'Day watch begins.': 'companion.line.timekeeper.morning.2',
  'Midday check.': 'companion.line.timekeeper.afternoon.1',
  'Hours are steady.': 'companion.line.timekeeper.afternoon.2',
  'Evening hours.': 'companion.line.timekeeper.evening.1',
  'Wind the dial.': 'companion.line.timekeeper.evening.2',
  'Night watch.': 'companion.line.timekeeper.night.1',
  'Stars keep time too.': 'companion.line.timekeeper.night.2',
  'Tempo noted.': 'companion.line.timekeeper.music.1',
  'In time.': 'companion.line.timekeeper.music.2',
  'Logged.': 'companion.line.timekeeper.study.1',
  'Progress stamped.': 'companion.line.timekeeper.study.2',
  'Milestone clocked.': 'companion.line.timekeeper.levelUp.1',
  'Level advanced.': 'companion.line.timekeeper.levelUp.2',
  'Yes?': 'companion.line.timekeeper.click.1',
  'On the hour.': 'companion.line.timekeeper.click.2',
  'Listening.': 'companion.line.timekeeper.click.3',
  'Still climbing.': 'companion.line.aero.idle.1',
  'Wall or ceiling?': 'companion.line.aero.idle.2',
  'Hmm.': 'companion.line.aero.idle.3',
  'Morning climb!': 'companion.line.aero.morning.1',
  'Up we go.': 'companion.line.aero.morning.2',
  'Climb to the beat.': 'companion.line.aero.music.1',
  'Higher!': 'companion.line.aero.music.2',
  'You study; I scale.': 'companion.line.aero.study.1',
  'Frame feels sturdy.': 'companion.line.aero.study.2',
  'Secret strength!': 'companion.line.aero.levelUp.1',
  'You leveled — celebrate.': 'companion.line.aero.levelUp.2',
  'Climb show?': 'companion.line.aero.click.2',
  'Hehe.': 'companion.line.aero.click.3',
  'Signal acquired.': 'companion.line.navi.idle.1',
  'Channel open.': 'companion.line.navi.idle.2',
  'Boot sequence… morning.': 'companion.line.navi.morning.1',
  'Link online.': 'companion.line.navi.morning.2',
  'Night band clear.': 'companion.line.navi.night.1',
  'Low power mode?': 'companion.line.navi.night.2',
  'Audio channel locked.': 'companion.line.navi.music.1',
  'Waveform pretty.': 'companion.line.navi.music.2',
  'Data ingested.': 'companion.line.navi.study.1',
  'Knowledge uplink.': 'companion.line.navi.study.2',
  'Level packet received.': 'companion.line.navi.levelUp.1',
  'Upgrade complete.': 'companion.line.navi.levelUp.2',
  'Ready.': 'companion.line.navi.click.1',
  'Command?': 'companion.line.navi.click.2',
  'Ping.': 'companion.line.navi.click.3',
  'Bookmark ready.': 'companion.line.buddy.idle.bookmark',
  'Page by page.': 'companion.line.buddy.click.pageByPage',
  'Warm spot found.': 'companion.line.critter.idle.warmSpot',
  'Tail swish.': 'companion.line.critter.click.tail',
  'Tick, tock, study o’clock.': 'companion.line.timekeeper.idle.studyOclock',
  'Right on time.': 'companion.line.timekeeper.click.onTime',
  'Need a hand? I know every shortcut.': 'companion.line.assistant.idle.1',
  'Five minutes free? I have a quick quiz ready.': 'companion.line.assistant.idle.2',
  'Tip: double-click me for my second trick.': 'companion.line.assistant.idle.3',
  'Good morning! Your cards missed you.': 'companion.line.assistant.morning',
  'Afternoon check-in: one quick deck?': 'companion.line.assistant.afternoon',
  'Evening already? Let us wrap up a deck.': 'companion.line.assistant.evening',
  'Studying late? I will keep the screen glowing.': 'companion.line.assistant.night',
  'Nice reading. I bookmarked your place.': 'companion.line.assistant.study',
  'Card cleared. Filed it for you.': 'companion.line.assistant.flashcard',
  'Level up! Cue the glossy fanfare.': 'companion.line.assistant.levelUp',
  'Hello again!': 'companion.line.assistant.click.1',
  'How can I help?': 'companion.line.assistant.click.2',
  'Packet received.': 'companion.line.navi.idle.packet',
  'Signal strong.': 'companion.line.navi.click.signal',
  'Start review': 'companion.routine.startReview',
  "Let's review": 'companion.routine.letsReview',
  'Cards ready': 'companion.routine.cardsReady',
  'Deep focus': 'companion.routine.deepFocus',
  'Quiet desk': 'companion.routine.quietDesk',
  'Focus mode': 'companion.routine.focusMode',
  'Particles dimmed · Library open': 'companion.routine.focusModeBody',
  'Weather toggle': 'companion.routine.weatherToggle',
  'Chasing weather': 'companion.routine.chasingWeather',
  'Critter': 'companion.routine.critter',
  'Particles toggled': 'companion.routine.particlesToggled',
  'Weather dance': 'companion.routine.weatherDance',
  'Dance!': 'companion.routine.dance',
  'Exploring': 'companion.routine.exploring',
  'Open calendar': 'companion.routine.openCalendar',
  'Clock in': 'companion.routine.clockIn',
  'Logging progress': 'companion.routine.loggingProgress',
  'Climb show': 'companion.routine.climbShow',
  'Scaling the desktop frame': 'companion.routine.scalingFrame',
  'Still climbing': 'companion.routine.stillClimbing',
  'Cheer': 'companion.routine.cheer',
  'Secret OS discovered': 'companion.routine.secretFound',
  'Climbing the frame': 'companion.routine.climbingFrame',
  'Morning greeting': 'companion.routine.morningGreeting',
  'Good morning': 'companion.routine.goodMorning',
  'Timekeeper': 'companion.routine.timekeeper',
  'Day watch begins': 'companion.routine.dayWatchBegins',
  'Music jam': 'companion.routine.musicJam',
  'Feeling the music': 'companion.routine.feelingMusic',
  'Idle stretch': 'companion.routine.idleStretch',
  'Still here': 'companion.routine.stillHere',
  'Day watch': 'companion.routine.dayWatch',
  'Evening hours': 'companion.routine.eveningHours',
  'Night watch': 'companion.routine.nightWatch',
};

/** The UI-language form of a built-in companion line, or `text` unchanged. */
export function buddyText(text: string): string;
export function buddyText(text: string | undefined): string | undefined;
export function buddyText(text: string | undefined): string | undefined {
  if (text == null) return text;
  const key = BUILTIN_TEXT[text];
  return key ? t(key) : text;
}

/** Every English line this module translates (for tests). */
export const BUILTIN_TEXT_KEYS: Readonly<Record<string, string>> = BUILTIN_TEXT;
