/**
 * The FSRS-5 optimiser, on synthetic review logs whose true weights are known.
 *
 * The logs are generated by the app's own FSRS model under a set of "true"
 * weights that differ from the defaults, with recall drawn from a seeded
 * generator. A correct optimiser, started from the defaults, must then:
 * predict those reviews better than the defaults do; land close to how well
 * the true weights predict them; give the same answer every time; and have a
 * gradient that agrees with finite differences.
 */
import { describe, expect, it } from 'vitest';

import {
  DEFAULT_FSRS_WEIGHTS,
  fsrsInitialMemory,
  fsrsInterval,
  fsrsRetrievability,
  fsrsReview,
  fsrsShortTermReview,
  isValidFsrsWeights,
  type FsrsGrade,
} from '../fsrs';
import {
  buildTrainingSequences,
  countScoredReviews,
  evaluateFsrsWeights,
  fsrsLossGradient,
  holdoutCutoff,
  MIN_HOLDOUT_REVIEWS,
  MIN_OPTIMIZER_REVIEWS,
  optimizeFsrsWeights,
  optimizeFsrsWithHoldout,
  pretrainInitialStability,
  selectTrainingRows,
  splitHeldOut,
  type FsrsLogRow,
} from '../fsrsOptimizer';
import {
  dailyReviewRate,
  retentionWorkloadCurve,
  simulateRetentionWorkload,
} from '../fsrsWorkload';
import type { LocalSrsRating } from '../localSrs';

const DAY = 24 * 60 * 60 * 1000;
const T0 = Date.UTC(2026, 0, 1, 12);

const TRUE_WEIGHTS: number[] = (() => {
  const w = [...DEFAULT_FSRS_WEIGHTS];
  w[0] = 0.25;
  w[1] = 0.9;
  w[2] = 2.2;
  w[3] = 9.5;
  w[8] = 1.9;
  w[10] = 0.8;
  w[11] = 1.3;
  return w;
})();

function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), a | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const RATING: Record<FsrsGrade, LocalSrsRating> = { 1: 'again', 2: 'hard', 3: 'good', 4: 'easy' };

/**
 * A synthetic log: `cards` cards reviewed for `days` days under `weights`, each
 * card first seen on a day in `[0, spread)`.
 */
function synthLog(weights: readonly number[], cards: number, days: number, seed: number, spread = 20): FsrsLogRow[] {
  const random = rng(seed);
  const rows: FsrsLogRow[] = [];
  for (let c = 0; c < cards; c += 1) {
    const cardId = `card-${c}`;
    const u = random();
    const first: FsrsGrade = u < 0.15 ? 1 : u < 0.25 ? 2 : u < 0.9 ? 3 : 4;
    let memory = fsrsInitialMemory(first, weights);
    let day = Math.floor(random() * spread);
    rows.push({ cardId, at: T0 + day * DAY, rating: RATING[first], isNew: true });
    for (;;) {
      // Scheduled near the model's own 90% interval, with some spread so the
      // log covers more than one point of each forgetting curve.
      const target = fsrsInterval(memory.stability, 0.9) * (0.6 + random() * 0.9);
      const interval = Math.max(1, Math.round(target));
      day += interval;
      if (day > days) break;
      const recalled = random() < fsrsRetrievability(memory.stability, interval);
      let grade: FsrsGrade = 1;
      if (recalled) {
        const g = random();
        grade = g < 0.1 ? 2 : g < 0.93 ? 3 : 4;
      }
      rows.push({ cardId, at: T0 + day * DAY, rating: RATING[grade] });
      memory = fsrsReview(memory, grade, interval, weights);
      if (grade === 1) {
        // The relearning step, ten minutes later, answered Good.
        rows.push({ cardId, at: T0 + day * DAY + 10 * 60 * 1000, rating: 'good' });
        memory = fsrsShortTermReview(memory, 3, weights);
      }
    }
  }
  return rows;
}

const LOG = synthLog(TRUE_WEIGHTS, 450, 400, 11);
const SEQUENCES = buildTrainingSequences(LOG);

describe('training sequences', () => {
  it('groups by card, measures whole days, and splits on a reset', () => {
    const rows: FsrsLogRow[] = [
      { cardId: 'b', at: T0 + 3 * DAY, rating: 'good' },
      { cardId: 'b', at: T0, rating: 'good', isNew: true },
      { cardId: 'b', at: T0 + 10 * 60 * 1000, rating: 'good' },
      // Reset: a new life of the same card.
      { cardId: 'b', at: T0 + 10 * DAY, rating: 'again', isNew: true },
      { cardId: 'b', at: T0 + 12 * DAY, rating: 'hard' },
      // A history with no first review cannot be replayed.
      { cardId: 'a', at: T0, rating: 'good' },
      { cardId: 'a', at: T0 + DAY, rating: 'good' },
    ];
    expect(buildTrainingSequences(rows)).toEqual([
      [
        { grade: 3, deltaDays: 0 },
        { grade: 3, deltaDays: 0 },
        { grade: 3, deltaDays: 3 },
      ],
      [
        { grade: 1, deltaDays: 0 },
        { grade: 2, deltaDays: 2 },
      ],
    ]);
  });

  it('counts a day from the configured boundary, not from midnight UTC', () => {
    // 03:00 and 05:00 local are different study days when the day starts at 04:00.
    const rows: FsrsLogRow[] = [
      { cardId: 'x', at: Date.UTC(2026, 0, 1, 3), rating: 'good', isNew: true },
      { cardId: 'x', at: Date.UTC(2026, 0, 1, 5), rating: 'good' },
    ];
    expect(buildTrainingSequences(rows, { dayStartHour: 4 })[0][1].deltaDays).toBe(1);
    expect(buildTrainingSequences(rows, { dayStartHour: 0 })[0][1].deltaDays).toBe(0);
  });

  it('has enough synthetic data to fit', () => {
    expect(countScoredReviews(SEQUENCES)).toBeGreaterThan(1500);
  });
});

describe('the gradient', () => {
  it('matches central finite differences on every weight', () => {
    const sample = SEQUENCES.slice(0, 60);
    const at = [...DEFAULT_FSRS_WEIGHTS];
    const { gradient } = fsrsLossGradient(at, sample);
    for (let i = 0; i < at.length; i += 1) {
      const h = Math.max(1e-6, Math.abs(at[i]) * 1e-5);
      const up = [...at];
      const down = [...at];
      up[i] += h;
      down[i] -= h;
      const numeric = (evaluateFsrsWeights(up, sample).logLoss - evaluateFsrsWeights(down, sample).logLoss) / (2 * h);
      expect(gradient[i], `w${i}`).toBeCloseTo(numeric, 4);
    }
  });
});

describe('optimizeFsrsWeights', () => {
  const first = optimizeFsrsWeights(SEQUENCES);

  it('predicts the log better than the defaults, and nearly as well as the truth', () => {
    expect(first.status).toBe('ok');
    expect(first.improved).toBe(true);
    expect(first.after.logLoss).toBeLessThan(first.before.logLoss);
    const truth = evaluateFsrsWeights(TRUE_WEIGHTS, SEQUENCES).logLoss;
    expect(first.after.logLoss).toBeLessThan(truth + 0.01);
    expect(isValidFsrsWeights(first.weights)).toBe(true);
  });

  it('is deterministic', () => {
    expect(optimizeFsrsWeights(SEQUENCES)).toEqual(first);
  });

  it('recovers the initial stabilities in the right order and near the truth', () => {
    const s0 = pretrainInitialStability(SEQUENCES);
    expect([...s0]).toEqual([...s0].sort((a, b) => a - b));
    expect(s0[2]).toBeGreaterThan(TRUE_WEIGHTS[2] * 0.6);
    expect(s0[2]).toBeLessThan(TRUE_WEIGHTS[2] * 1.6);
  });

  it('refuses to fit a log that is too small, and says so', () => {
    const tiny = buildTrainingSequences(synthLog(TRUE_WEIGHTS, 8, 60, 3));
    expect(countScoredReviews(tiny)).toBeLessThan(MIN_OPTIMIZER_REVIEWS);
    const result = optimizeFsrsWeights(tiny);
    expect(result.status).toBe('insufficient-data');
    expect(result.weights).toEqual([...DEFAULT_FSRS_WEIGHTS]);
    expect(result.improved).toBe(false);
  });
});

describe('held-out validation and what may train', () => {
  /**
   * New cards keep arriving over most of the year, as in real use, so the
   * latest 20% of reviews is a mix of young and old cards rather than only the
   * longest intervals of one cohort.
   */
  const SPREAD_LOG = synthLog(TRUE_WEIGHTS, 600, 400, 11, 300);
  const clean = SPREAD_LOG.map((row) => ({ mode: 'review', ...row }));
  /** The same log with game and practice answers mixed in. */
  const entries = [
    ...clean,
    // A game answer on every 5th card and a practice answer on every 7th: never training data.
    ...SPREAD_LOG.filter((_, i) => i % 5 === 0).map((row) => ({ mode: 'game', cardId: row.cardId, at: row.at + 1, correct: false })),
    ...SPREAD_LOG.filter((_, i) => i % 7 === 0).map((row) => ({ mode: 'learn', cardId: row.cardId, at: row.at + 2, rating: 'again' as const })),
    // A due card graded from a game: a review row, but not a recall test.
    ...SPREAD_LOG.filter((_, i) => i % 9 === 0).map((row) => ({ mode: 'review', source: 'game', cardId: row.cardId, at: row.at + 3, rating: 'again' as const })),
  ];
  const result = optimizeFsrsWithHoldout(entries);

  it('trains only on review-surface reviews', () => {
    const { rows, excluded } = selectTrainingRows(entries);
    expect(rows).toHaveLength(SPREAD_LOG.length);
    expect(excluded).toBe(entries.length - SPREAD_LOG.length);
    expect(rows.every((row) => !('mode' in row))).toBe(true);
  });

  it('gives the same fit whether or not game and practice rows are in the log', () => {
    const plain = optimizeFsrsWithHoldout(clean);
    expect({ ...result, excluded: 0 }).toEqual(plain);
    expect(result.excluded).toBeGreaterThan(0);
  });

  it('holds out the latest ~20% of reviews by time', () => {
    const rows = Array.from({ length: 10 }, (_, i) => ({ at: T0 + i * DAY }));
    expect(holdoutCutoff(rows, 0.2)).toBe(T0 + 8 * DAY);
    expect(holdoutCutoff([], 0.2)).toBe(Number.POSITIVE_INFINITY);
    const { rows: real } = selectTrainingRows(clean);
    const cutoff = holdoutCutoff(real);
    const late = real.filter((row) => row.at >= cutoff).length / real.length;
    expect(late).toBeGreaterThan(0.18);
    expect(late).toBeLessThan(0.25);
  });

  it('trains on the past of each history and scores only held-out reviews', () => {
    const rows: FsrsLogRow[] = [
      { cardId: 'a', at: T0, rating: 'good', isNew: true },
      { cardId: 'a', at: T0 + 2 * DAY, rating: 'good' },
      { cardId: 'a', at: T0 + 9 * DAY, rating: 'again' },
      { cardId: 'b', at: T0 + 10 * DAY, rating: 'good', isNew: true },
      { cardId: 'b', at: T0 + 12 * DAY, rating: 'good' },
    ];
    const seqs = buildTrainingSequences(rows, { holdoutFrom: T0 + 9 * DAY });
    const { train, heldOut } = splitHeldOut(seqs);
    expect(train).toEqual([[{ grade: 3, deltaDays: 0 }, { grade: 3, deltaDays: 2 }]]);
    expect(heldOut).toHaveLength(2);
    // Card a's first two reviews are replayed for state but only its lapse is scored.
    expect(evaluateFsrsWeights(DEFAULT_FSRS_WEIGHTS, heldOut, { heldOutOnly: true }).reviews).toBe(2);
    expect(evaluateFsrsWeights(DEFAULT_FSRS_WEIGHTS, heldOut).reviews).toBe(3);
  });

  it('offers a fit only when it beats the current weights on the unseen latest reviews', () => {
    expect(result.status).toBe('ok');
    expect(result.trainReviews).toBeGreaterThanOrEqual(MIN_OPTIMIZER_REVIEWS);
    expect(result.current.reviews).toBeGreaterThanOrEqual(MIN_HOLDOUT_REVIEWS);
    expect(result.fitted.reviews).toBe(result.current.reviews);
    // The defaults are wrong for this learner, and the fit generalises: on
    // reviews it never saw it lands about where the true weights do.
    expect(result.improved).toBe(true);
    expect(result.fitted.logLoss).toBeLessThan(result.current.logLoss);
    const truth = optimizeFsrsWithHoldout(clean, { current: TRUE_WEIGHTS }).current.logLoss;
    expect(result.fitted.logLoss).toBeLessThan(truth + 0.005);
    expect(result.weights).not.toEqual([...DEFAULT_FSRS_WEIGHTS]);
    expect(isValidFsrsWeights(result.weights)).toBe(true);
  });

  it('keeps the current weights when the fit only looks better on its own training reviews', () => {
    // Every card of LOG starts in its first 20 days, so the latest 20% is only
    // the longest intervals: the fit improves its training loss but predicts
    // that unseen tail worse than the defaults. Validated on training data, it
    // would have been offered.
    const rows = LOG.map((row) => ({ mode: 'review', ...row }));
    const tail = optimizeFsrsWithHoldout(rows);
    expect(tail.status).toBe('ok');
    expect(tail.improved).toBe(false);
    expect(tail.fitted.logLoss).toBeGreaterThanOrEqual(tail.current.logLoss);
    expect(tail.weights).toEqual([...DEFAULT_FSRS_WEIGHTS]);
    // A current set that already is the fit cannot be beaten by the same fit.
    const again = optimizeFsrsWithHoldout(clean, { current: result.weights });
    expect(again.improved).toBe(false);
    expect(again.weights).toEqual(result.weights);
  });

  it('is deterministic, and reports progress without changing the answer', () => {
    const seen: number[] = [];
    const tracked = optimizeFsrsWithHoldout(entries, { onProgress: (f) => seen.push(f) });
    expect(tracked).toEqual(result);
    expect(seen.length).toBeGreaterThan(1);
    expect(seen[seen.length - 1]).toBeCloseTo(1, 1);
    expect([...seen].sort((a, b) => a - b)).toEqual(seen);
  });

  it('refuses a log too small to split, and says which side is short', () => {
    const tiny = synthLog(TRUE_WEIGHTS, 8, 60, 3).map((row) => ({ mode: 'review', ...row }));
    const refused = optimizeFsrsWithHoldout(tiny);
    expect(refused.status).toBe('insufficient-data');
    expect(refused.shortOf).toBe('train');
    expect(refused.improved).toBe(false);
    expect(refused.weights).toEqual([...DEFAULT_FSRS_WEIGHTS]);
  });
});

describe('retention workload', () => {
  it('asks for more reviews as retention rises, deterministically', () => {
    const curve = retentionWorkloadCurve([0.8, 0.85, 0.9, 0.95]);
    for (let i = 1; i < curve.length; i += 1) {
      expect(curve[i].reviewsPerCard).toBeGreaterThan(curve[i - 1].reviewsPerCard);
      expect(curve[i].averageRecall).toBeGreaterThan(curve[i - 1].averageRecall);
    }
    expect(simulateRetentionWorkload(0.9)).toEqual(simulateRetentionWorkload(0.9));
  });

  it('sums the deck’s daily rate from its stabilities', () => {
    // At 90% the interval equals the stability, so a 10-day card is 0.1 a day.
    expect(dailyReviewRate([10, 10, 0.5], 0.9)).toBeCloseTo(0.1 + 0.1 + 1, 6);
    expect(dailyReviewRate([10], 0.95)).toBeGreaterThan(dailyReviewRate([10], 0.9));
  });
});
